//! Decision-AI feasibility shell (experiment E1).
//!
//! Proves the full inference chain the built-in decision model will need:
//! `ort` statically links ONNX Runtime into the binary, a tiny fixture model
//! (embedded at compile time via `include_bytes!` — no runtime file access,
//! no network) loads into a lazily-created [`Session`], and a real forward
//! pass is served over Tauri IPC.
//!
//! The fixture is a single MatMul over float32[1,8]: `y = x @ W` with
//! `W[i][j] = 2.0` when `i == j` else `0.5`, i.e. `y[i] = 1.5*x[i] +
//! 0.5*sum(x)`. The output-to-suggestion mapping (`heading_sector` /
//! `speed_setting` / `fire`) is placeholder semantics chosen to exercise
//! argmax / threshold paths, not tactical advice — the real model replaces
//! both the weights and the head layout later.
//!
//! Concurrency: `Session::run` takes `&mut self` in this `ort` line (ONNX
//! Runtime internals are not thread-safe), so the fixture session lives in a
//! [`Mutex`] behind a [`OnceLock`] — created once per process, inference
//! serialized. Fine for an E1 shell; a real model will shard per-thread
//! sessions or batch requests.

use std::sync::{Mutex, OnceLock};

use ort::{session::Session, value::Tensor};
use wowsp_tauri_shared::{DecisionAiStatus, DecisionDummyState, DecisionDummySuggestion};

/// The `ort` crate pin from the root Cargo.toml. Dependency versions are not
/// exposed through `env!` at compile time and ort publishes no public
/// version constant, so this is synced manually — the test below only echoes
/// it, it cannot detect drift.
const ORT_CRATE_VERSION: &str = "2.0.0-rc.13";

/// Fixture model bytes: the ONNX graph described in the module docs (369
/// bytes on disk). Generated by a one-off Python `onnx` script during
/// experiment E1; regenerate only with a matching expected-output update in
/// the tests below. `pub(crate)` so the G4 serving tests can drive the
/// fixture path through [`DecisionModel`].
pub(crate) const FIXTURE_MODEL: &[u8] = include_bytes!("fixtures/decision_ai_tiny.onnx");

/// Fixture input width — also the output width (single MatMul). Tied to the
/// 8 fields of [`DecisionDummyState`].
const STATE_DIM: usize = 8;

static FIXTURE_SESSION: OnceLock<Result<Mutex<Session>, String>> = OnceLock::new();

/// Build a session from raw ONNX bytes. Isolated so tests can spin up their
/// own session instead of going through the process-global fixture.
/// (`commit_from_memory` — this ort RC renamed the rc.9-era
/// `commit_from_bytes`.)
fn session_from_bytes(bytes: &[u8]) -> Result<Session, String> {
    let mut builder = Session::builder().map_err(|e| format!("create session builder: {e}"))?;
    builder
        .commit_from_memory(bytes)
        .map_err(|e| format!("load ONNX model: {e}"))
}

/// The process-global fixture session, created on first use.
fn fixture_session() -> Result<&'static Mutex<Session>, String> {
    FIXTURE_SESSION
        .get_or_init(|| session_from_bytes(FIXTURE_MODEL).map(Mutex::new))
        .as_ref()
        .map_err(Clone::clone)
}

/// Flatten the dummy state into the model's input row, in
/// [`DecisionDummyState`] field order.
fn state_to_input(state: &DecisionDummyState) -> [f32; STATE_DIM] {
    [
        state.own_heading_sin,
        state.own_heading_cos,
        state.own_speed,
        state.enemy_bearing_sin,
        state.enemy_bearing_cos,
        state.enemy_distance,
        state.own_hp_fraction,
        state.target_visible,
    ]
}

/// Run one forward pass of `session` and return the flat output row.
/// Shape-checked: the fixture must answer float32[1, STATE_DIM].
fn forward(session: &mut Session, input: &[f32; STATE_DIM]) -> Result<[f32; STATE_DIM], String> {
    let tensor = Tensor::from_array(([1usize, STATE_DIM], input.to_vec()))
        .map_err(|e| format!("build input tensor: {e}"))?;
    let outputs = session
        .run(ort::inputs!["x" => tensor])
        .map_err(|e| format!("run inference: {e}"))?;
    let view = outputs["y"]
        .try_extract_array::<f32>()
        .map_err(|e| format!("extract output: {e}"))?;
    if view.shape() != [1, STATE_DIM].as_slice() {
        return Err(format!(
            "unexpected output shape {:?}, expected [1, {STATE_DIM}]",
            view.shape()
        ));
    }
    let flat: Vec<f32> = view.iter().copied().collect();
    flat.try_into()
        .map_err(|v: Vec<f32>| format!("expected {STATE_DIM} outputs, got {}", v.len()))
}

// ── G4: session-source ladder + metadata-driven schema ─────────────────────
//
// The product path loads the trained fire model from the `decisions` model
// pack (`<cache>/decisions/fire_model.onnx`, see model_pack.rs) when it is
// installed and falls back to the embedded E1 fixture otherwise. BOTH
// schemas must run through one code path, so the loaded session's INPUT
// METADATA (names + declared shapes) — not the file's origin — decides the
// inference path:
//   * one input `x` of width 8            → E1 fixture dummy path
//   * `entity`[1,S,E] + `global_feat`[1,G]
//     + `mask`[1,S] → logitA/logitB       → E9 two-head fire path
// This also keeps a developer dropping the tiny fixture into the pack slot
// (or the pack shipping a placeholder) behaving identically.

/// Where a [`DecisionModel`]'s session bytes came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DecisionModelSource {
    /// The `decisions` model pack under the cache dir.
    Pack,
    /// The ONNX fixture embedded at compile time (experiment E1).
    Fixture,
}

impl DecisionModelSource {
    /// Wire value for the suggestion DTOs (`modelSource`).
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Pack => "pack",
            Self::Fixture => "fixture",
        }
    }
}

/// The input schema a loaded session speaks. Detected from session
/// metadata; the slot/dim fields carry what the actual file declared so a
/// re-trained model with wider slots still runs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DecisionModelKind {
    /// E1 fixture: input `x` float32[1,8] → output `y` [1,8].
    Fixture8,
    /// E9 two-head fire model: `entity`[1,SLOTS,ENTITY_DIM] +
    /// `global_feat`[1,GLOBAL_DIM] + `mask`[1,SLOTS] → `logitA` / `logitB`.
    Fire24 {
        slots: usize,
        entity_dim: usize,
        global_dim: usize,
    },
}

/// One loaded decision model: origin + schema + live session. Inference is
/// `&mut self` (ORT sessions are not thread-safe in this ort line), so the
/// shared instance lives behind a [`Mutex`].
pub struct DecisionModel {
    source: DecisionModelSource,
    detail: String,
    kind: DecisionModelKind,
    session: Session,
}

impl DecisionModel {
    /// Build from raw ONNX bytes, detecting the schema from the session's
    /// input/output metadata.
    pub fn from_bytes(
        source: DecisionModelSource,
        detail: impl Into<String>,
        bytes: &[u8],
    ) -> Result<Self, String> {
        let session = session_from_bytes(bytes)?;
        let kind = detect_kind(&session)?;
        Ok(Self {
            source,
            detail: detail.into(),
            kind,
            session,
        })
    }

    /// The G4 source ladder: `<cache>/decisions/fire_model.onnx` from the
    /// `decisions` model pack when installed, else the embedded E1 fixture.
    /// CACHED PER PROCESS — replacing the pack file mid-session needs an app
    /// restart (the stamp-checked pack download replaces the whole directory
    /// atomically, so a torn read is impossible, only a stale session).
    /// A load ERROR is sticky the same way: a corrupt pack model disables
    /// suggestions (with the error surfaced) until restart rather than
    /// silently falling back to the fixture.
    pub fn load_pack_or_fixture() -> Result<Self, String> {
        let pack_path = crate::paths::cache_dir()
            .map_err(|e| format!("resolve cache dir: {e}"))?
            .join("decisions")
            .join("fire_model.onnx");
        match std::fs::read(&pack_path) {
            Ok(bytes) => Self::from_bytes(
                DecisionModelSource::Pack,
                pack_path.to_string_lossy().into_owned(),
                &bytes,
            ),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                tracing::info!(
                    ?pack_path,
                    "no decisions model pack installed - falling back to the E1 fixture"
                );
                Self::from_bytes(
                    DecisionModelSource::Fixture,
                    "embedded fixture (E1, 369-byte MatMul)",
                    FIXTURE_MODEL,
                )
            },
            Err(e) => Err(format!("read {}: {e}", pack_path.to_string_lossy())),
        }
    }

    pub fn source(&self) -> DecisionModelSource {
        self.source
    }

    /// Human-facing provenance (file path / fixture label) for diagnostics.
    pub fn detail(&self) -> &str {
        &self.detail
    }

    pub fn kind(&self) -> &DecisionModelKind {
        &self.kind
    }

    /// E1 fixture inference: one [1,8] row in, one [1,8] row out.
    pub fn infer_fixture(&mut self, input: &[f32; STATE_DIM]) -> Result<[f32; STATE_DIM], String> {
        forward(&mut self.session, input)
    }

    /// E9 two-head fire inference. `entity` is the flat [SLOTS×ENTITY_DIM]
    /// row-major matrix, `global`/`mask` the flat feature rows. Returns
    /// (logitA "can fire", logitB "expert fires").
    pub fn infer_fire(
        &mut self,
        entity: &[f32],
        global: &[f32],
        mask: &[f32],
    ) -> Result<(f32, f32), String> {
        let DecisionModelKind::Fire24 {
            slots,
            entity_dim,
            global_dim,
        } = self.kind
        else {
            return Err("infer_fire on a non-fire-schema session".into());
        };
        if entity.len() != slots * entity_dim || global.len() != global_dim || mask.len() != slots {
            return Err(format!(
                "feature width mismatch: entity {} (want {}), global {} (want {}), mask {} (want {})",
                entity.len(),
                slots * entity_dim,
                global.len(),
                global_dim,
                mask.len(),
                slots
            ));
        }
        let entity_t = Tensor::from_array(([1usize, slots, entity_dim], entity.to_vec()))
            .map_err(|e| format!("build entity tensor: {e}"))?;
        let global_t = Tensor::from_array(([1usize, global_dim], global.to_vec()))
            .map_err(|e| format!("build global tensor: {e}"))?;
        let mask_t = Tensor::from_array(([1usize, slots], mask.to_vec()))
            .map_err(|e| format!("build mask tensor: {e}"))?;
        let outputs = self
            .session
            .run(ort::inputs![
                "entity" => entity_t,
                "global_feat" => global_t,
                "mask" => mask_t,
            ])
            .map_err(|e| format!("run inference: {e}"))?;
        let mut logits = [0.0f32; 2];
        for (idx, name) in ["logitA", "logitB"].iter().enumerate() {
            let v = outputs
                .get(name)
                .ok_or_else(|| format!("output '{name}' missing"))?;
            let view = v
                .try_extract_array::<f32>()
                .map_err(|e| format!("extract {name}: {e}"))?;
            let flat: Vec<f32> = view.iter().copied().collect();
            // The exported heads squeeze to [1]; accept [1] or [1,1]. A bad
            // pack model must error, never panic (a panic here would poison
            // the shared session mutex for the rest of the process).
            if flat.len() != 1 {
                return Err(format!(
                    "output {name} has {} values, expected 1 (shape {:?})",
                    flat.len(),
                    view.shape()
                ));
            }
            logits[idx] = flat[0];
        }
        Ok((logits[0], logits[1]))
    }
}

/// Read one declared tensor dimension (`-1`/unknown → `default`).
fn declared_dim(shape: &[i64], idx: usize, default: usize) -> usize {
    shape
        .get(idx)
        .and_then(|d| usize::try_from(*d).ok())
        .filter(|d| *d > 0)
        .unwrap_or(default)
}

/// Classify a live session by its input/output metadata. Unknown schemas are
/// a hard error (better than running a wrong-shaped forward).
fn detect_kind(session: &Session) -> Result<DecisionModelKind, String> {
    let inputs = session.inputs();
    let names: Vec<&str> = inputs.iter().map(|i| i.name()).collect();
    let describe = || -> String {
        inputs
            .iter()
            .map(|i| format!("{}:{}", i.name(), i.dtype()))
            .collect::<Vec<_>>()
            .join(", ")
    };
    if names.contains(&"entity") && names.contains(&"global_feat") && names.contains(&"mask") {
        let shape_of = |name: &str| -> Vec<i64> {
            inputs
                .iter()
                .find(|i| i.name() == name)
                .and_then(|i| i.dtype().tensor_shape().map(|s| s.to_vec()))
                .unwrap_or_default()
        };
        let entity_shape = shape_of("entity");
        let global_shape = shape_of("global_feat");
        let kind = DecisionModelKind::Fire24 {
            slots: declared_dim(&entity_shape, 1, 24),
            entity_dim: declared_dim(&entity_shape, 2, 10),
            global_dim: declared_dim(&global_shape, 1, 14),
        };
        let outputs: Vec<&str> = session.outputs().iter().map(|o| o.name()).collect();
        if !outputs.contains(&"logitA") || !outputs.contains(&"logitB") {
            return Err(format!(
                "fire model is missing its logitA/logitB heads (outputs: {outputs:?})"
            ));
        }
        return Ok(kind);
    }
    if names.len() == 1 && names[0] == "x" {
        let width = inputs[0]
            .dtype()
            .tensor_shape()
            .and_then(|s| s.last().copied())
            .and_then(|d| usize::try_from(d).ok())
            .unwrap_or(0);
        if width == STATE_DIM {
            return Ok(DecisionModelKind::Fixture8);
        }
        return Err(format!(
            "fixture-like input x has width {width}, expected {STATE_DIM}"
        ));
    }
    Err(format!(
        "unsupported decision model schema: [{}]",
        describe()
    ))
}

/// The process-global shared model (pack → fixture ladder), created on first
/// use. Tests build their own sessions instead of touching this cache.
static SHARED_MODEL: OnceLock<Result<Mutex<DecisionModel>, String>> = OnceLock::new();

/// The shared [`DecisionModel`] behind the standard ladder.
pub fn shared_model() -> Result<&'static Mutex<DecisionModel>, String> {
    SHARED_MODEL
        .get_or_init(|| DecisionModel::load_pack_or_fixture().map(Mutex::new))
        .as_ref()
        .map_err(Clone::clone)
}

/// Index of the largest element (first one on ties — deterministic).
fn argmax(xs: &[f32]) -> usize {
    let mut best = 0;
    for (i, x) in xs.iter().enumerate() {
        if *x > xs[best] {
            best = i;
        }
    }
    best
}

/// Map the fixture model's 8 output logits to the dummy suggestion. A pure
/// function so tests can drive it without a session:
///   logits 0..4 → heading sector (argmax, 0-3)
///   logits 4..7 → throttle level (argmax, 0-2)
///   logit 7     → fire vote (> 0)
fn map_logits(y: &[f32; STATE_DIM]) -> DecisionDummySuggestion {
    DecisionDummySuggestion {
        heading_sector: argmax(&y[0..4]) as u32,
        speed_setting: argmax(&y[4..7]) as u32,
        fire: y[STATE_DIM - 1] > 0.0,
    }
}

/// Decision-AI runtime status: `ort` crate version, native ONNX Runtime
/// build info, and whether the embedded fixture loaded into a live session.
#[tauri::command]
pub fn decision_ai_status() -> Result<DecisionAiStatus, String> {
    Ok(DecisionAiStatus {
        ort_version: ORT_CRATE_VERSION.to_string(),
        runtime_info: ort::info().to_string(),
        fixture_loaded: fixture_session().is_ok(),
    })
}

/// One forward pass of the fixture model over a dummy battle state — the
/// end-to-end E1 chain: embedded bytes → session → inference → suggestion.
#[tauri::command]
pub fn decision_ai_suggest(state: DecisionDummyState) -> Result<DecisionDummySuggestion, String> {
    let input = state_to_input(&state);
    let session = fixture_session()?;
    let mut session = session
        .lock()
        .map_err(|_| "fixture session mutex poisoned")?;
    let y = forward(&mut session, &input)?;
    Ok(map_logits(&y))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Reference output for input [1..8]: `y[i] = 1.5*x[i] + 0.5*sum(x)` =
    /// `1.5*x[i] + 18`. All values are dyadic rationals well inside f32's
    /// exact-integer/half range, so every intermediate of the MatMul is
    /// exactly representable and exact equality is meaningful.
    const EXPECTED_Y: [f32; STATE_DIM] = [19.5, 21.0, 22.5, 24.0, 25.5, 27.0, 28.5, 30.0];

    /// Load the embedded fixture → session → one forward pass → assert the
    /// output shape AND the exact expected values.
    #[test]
    fn fixture_forward_matches_reference() {
        let mut session = session_from_bytes(FIXTURE_MODEL).expect("load fixture session");
        let input = [1.0f32, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0];
        let tensor =
            Tensor::from_array(([1usize, STATE_DIM], input.to_vec())).expect("build input tensor");
        let outputs = session
            .run(ort::inputs!["x" => tensor])
            .expect("run inference");
        let y = outputs["y"]
            .try_extract_array::<f32>()
            .expect("extract output");
        assert_eq!(y.shape(), &[1, STATE_DIM]);
        let got: Vec<f32> = y.iter().copied().collect();
        assert_eq!(got.as_slice(), EXPECTED_Y);
    }

    /// The command path through the process-global session produces the
    /// analytically-derived suggestion for a crafted state:
    /// x = [0, 1, 0.5, -1, 0, 1, 1, 1] → sum = 3.5 → y[i] = 1.5*x[i] + 1.75
    ///   = [1.75, 3.25, 2.5, 0.25, 1.75, 3.25, 3.25, 3.25]
    /// argmax(y[0..4]) = 1, argmax(y[4..7]) = 1 (first of the 3.25 tie),
    /// y[7] > 0 → fire.
    #[test]
    fn suggest_runs_the_full_chain() {
        let state = DecisionDummyState {
            own_heading_sin: 0.0,
            own_heading_cos: 1.0,
            own_speed: 0.5,
            enemy_bearing_sin: -1.0,
            enemy_bearing_cos: 0.0,
            enemy_distance: 1.0,
            own_hp_fraction: 1.0,
            target_visible: 1.0,
        };
        let suggestion = decision_ai_suggest(state).expect("suggest");
        assert_eq!(
            suggestion,
            DecisionDummySuggestion {
                heading_sector: 1,
                speed_setting: 1,
                fire: true,
            }
        );
    }

    /// The logit mapping is a pure function — drive it directly with
    /// hand-picked logits, including the fire threshold at exactly 0.
    #[test]
    fn map_logits_picks_sector_speed_and_fire() {
        let s = map_logits(&[0.1, 0.2, 3.0, -1.0, 0.0, 2.5, 1.0, 0.25]);
        assert_eq!(s.heading_sector, 2);
        assert_eq!(s.speed_setting, 1);
        assert!(s.fire);

        // Sector 0 / speed 0 lead from the front; zero logit does not fire.
        let s = map_logits(&[5.0, 1.0, 0.0, 0.0, 9.0, 1.0, 2.0, 0.0]);
        assert_eq!(s.heading_sector, 0);
        assert_eq!(s.speed_setting, 0);
        assert!(!s.fire);

        let s = map_logits(&[-5.0, -1.0, -0.1, -9.0, -9.0, -0.5, -1.0, -3.0]);
        assert_eq!(s.heading_sector, 2);
        assert_eq!(s.speed_setting, 1);
        assert!(!s.fire);
    }

    /// Status reports the pinned ort version and a live fixture session.
    #[test]
    fn status_reports_loaded_fixture() {
        let status = decision_ai_status().expect("status");
        assert_eq!(status.ort_version, ORT_CRATE_VERSION);
        assert!(status.fixture_loaded);
        assert!(!status.runtime_info.is_empty());
    }

    // ── G4: metadata-driven schema detection + source ladder ──────────────────

    /// The embedded fixture loads through [`DecisionModel`] and is
    /// classified by its metadata (input `x` [1,8]) as the E1 dummy schema;
    /// one fixture inference round-trips.
    #[test]
    fn decision_model_classifies_and_runs_the_fixture() {
        let mut model = DecisionModel::from_bytes(
            DecisionModelSource::Fixture,
            "fixture under test",
            FIXTURE_MODEL,
        )
        .expect("load fixture model");
        assert_eq!(model.source(), DecisionModelSource::Fixture);
        assert_eq!(model.source().as_str(), "fixture");
        assert_eq!(model.kind(), &DecisionModelKind::Fixture8);
        let y = model
            .infer_fixture(&[1.0f32, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0])
            .expect("fixture inference");
        assert_eq!(y.as_slice(), EXPECTED_Y);
        // A fixture-classified session refuses the fire path instead of
        // running a wrong-shaped forward.
        assert!(
            model
                .infer_fire(&[0.0; 240], &[0.0; 14], &[0.0; 24])
                .is_err()
        );
    }

    /// Garbage bytes are a load error, and an ONNX graph whose inputs match
    /// neither schema is a detection error — never a silent wrong path.
    #[test]
    fn decision_model_rejects_unknown_schemas() {
        assert!(
            DecisionModel::from_bytes(DecisionModelSource::Fixture, "garbage", &[0u8, 1, 2, 3, 4],)
                .is_err()
        );
    }

    /// G4 against the real trained model — run with
    /// `WOWSP_TEST_MODEL=<out/fire_model/fp32.onnx> cargo test -p wowsp_tauri
    /// g4_real -- --ignored --nocapture`. Proves the metadata classifier
    /// recognises the E9 export (entity/global_feat/mask + logitA/logitB)
    /// and that [`DecisionModel::infer_fire`] answers the E9 sample input
    /// consistently with the raw-session E9 test.
    #[test]
    #[ignore = "needs the trained model from scripts/experiments/train_fire_model.py"]
    fn g4_real_model_through_decision_model() {
        let out_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../../scripts/experiments/out/fire_model");
        let model_path = match std::env::var("WOWSP_TEST_MODEL") {
            Ok(p) => std::path::PathBuf::from(p),
            Err(_) => out_dir.join("fp32.onnx"),
        };
        let bytes = match std::fs::read(&model_path) {
            Ok(b) => b,
            Err(_) => {
                eprintln!("[g4] {} not found - skipping", model_path.display());
                return;
            },
        };
        let mut model = DecisionModel::from_bytes(
            DecisionModelSource::Pack,
            model_path.to_string_lossy().into_owned(),
            &bytes,
        )
        .expect("load real model");
        assert_eq!(model.source().as_str(), "pack");
        assert_eq!(
            model.kind(),
            &DecisionModelKind::Fire24 {
                slots: E9_SLOTS,
                entity_dim: E9_ENTITY_DIM,
                global_dim: E9_GLOBAL_DIM
            }
        );
        // Zero features, full mask: a finite answer (the training script's
        // all-masked NaN guard is an ONNX-side property — zeros cannot NaN).
        let entity = vec![0.0f32; E9_SLOTS * E9_ENTITY_DIM];
        let global = vec![0.0f32; E9_GLOBAL_DIM];
        let mask = vec![1.0f32; E9_SLOTS];
        let (la, lb) = model
            .infer_fire(&entity, &global, &mask)
            .expect("infer_fire on real model");
        assert!(la.is_finite() && lb.is_finite());
        eprintln!("[g4] real model logits A {la:.4} B {lb:.4} (zero features)");
    }

    // ── E9 step 3: load the REAL trained model through ort ──────────────────
    //
    // The E1 fixture above proves the runtime; these tests prove the rest of
    // the delivery loop: a model actually TRAINED by
    // `scripts/experiments/train_fire_model.py` (PyTorch → static-shape ONNX,
    // optional int8 dynamic quantization) loads into the same `ort` build and
    // answers a forward pass on a REAL featurized tick (the JSONL export of
    // E9 step 1, featurized by the training script into `sample_input.json`).
    // Both tests default to the worktree's experiment output directory and
    // skip when the files are absent; run explicitly with
    // `cargo test -p wowsp_tauri e9_real_model -- --ignored --nocapture`.

    /// Model input geometry — must mirror the training script's export
    /// (entity [1, 24, 10], global_feat [1, 14], mask [1, 24]).
    const E9_SLOTS: usize = 24;
    const E9_ENTITY_DIM: usize = 10;
    const E9_GLOBAL_DIM: usize = 14;
    /// Forward passes timed for the latency report (after 5 warmups).
    const E9_TIMING_RUNS: usize = 50;

    /// Load + forward one real model, asserting the output contract and
    /// reporting latency. Returns (logit_a, logit_b, p50_us, p95_us).
    fn e9_run_real_model(
        model_path: &std::path::Path,
        sample_path: &std::path::Path,
    ) -> Result<(f32, f32, u128, u128), String> {
        let bytes = std::fs::read(model_path).map_err(|e| format!("read model: {e}"))?;
        let mut session = session_from_bytes(&bytes)?;
        let sample: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(sample_path).map_err(|e| {
                format!(
                    "read {} (regenerate via train_fire_model.py): {e}",
                    sample_path.display()
                )
            })?)
            .map_err(|e| format!("parse sample_input.json: {e}"))?;
        let nums = |key: &str, want: usize| -> Result<Vec<f32>, String> {
            serde_json::from_value::<Vec<f32>>(sample[key].clone())
                .map_err(|e| format!("parse sample '{key}' as f32 array: {e}"))
                .and_then(|v| {
                    if v.len() == want {
                        Ok(v)
                    } else {
                        Err(format!(
                            "sample '{key}' has {} entries, expected {want}",
                            v.len()
                        ))
                    }
                })
        };
        // entity is serialized nested [SLOTS][ENTITY_DIM] (self-documenting);
        // global/mask are flat.
        let entity: Vec<f32> = serde_json::from_value::<Vec<Vec<f32>>>(sample["entity"].clone())
            .map_err(|e| format!("parse sample 'entity' as f32 matrix: {e}"))
            .and_then(|rows| {
                if rows.len() == E9_SLOTS && rows.iter().all(|r| r.len() == E9_ENTITY_DIM) {
                    Ok(rows.into_iter().flatten().collect())
                } else {
                    Err(format!(
                        "sample 'entity' is not [{E9_SLOTS}][{E9_ENTITY_DIM}]"
                    ))
                }
            })?;
        let global = nums("global", E9_GLOBAL_DIM)?;
        let mask = nums("mask", E9_SLOTS)?;
        let entity_t = ort::value::Tensor::from_array(([1usize, E9_SLOTS, E9_ENTITY_DIM], entity))
            .map_err(|e| format!("build entity tensor: {e}"))?;
        let global_t = ort::value::Tensor::from_array(([1usize, E9_GLOBAL_DIM], global))
            .map_err(|e| format!("build global tensor: {e}"))?;
        let mask_t = ort::value::Tensor::from_array(([1usize, E9_SLOTS], mask))
            .map_err(|e| format!("build mask tensor: {e}"))?;
        let run_once = |session: &mut Session| -> Result<(f32, f32), String> {
            let outputs = session
                .run(ort::inputs![
                    "entity" => entity_t.view(),
                    "global_feat" => global_t.view(),
                    "mask" => mask_t.view(),
                ])
                .map_err(|e| format!("run inference: {e}"))?;
            let mut logits = [0.0f32; 2];
            for (idx, name) in ["logitA", "logitB"].iter().enumerate() {
                let v = outputs
                    .get(name)
                    .ok_or_else(|| format!("output '{name}' missing"))?;
                let view = v
                    .try_extract_array::<f32>()
                    .map_err(|e| format!("extract {name}: {e}"))?;
                let flat: Vec<f32> = view.iter().copied().collect();
                // The exported heads squeeze to [1]; accept [1] or [1,1].
                assert_eq!(flat.len(), 1, "output {name} shape {:?}", view.shape());
                assert!(
                    flat[0].is_finite(),
                    "output {name} is not finite: {}",
                    flat[0]
                );
                logits[idx] = flat[0];
            }
            Ok((logits[0], logits[1]))
        };
        // Warmup, then timed forwards (single-threaded session use, mirroring
        // how a real tick-time suggestion would run).
        for _ in 0..5 {
            run_once(&mut session)?;
        }
        let mut micros: Vec<u128> = Vec::with_capacity(E9_TIMING_RUNS);
        for _ in 0..E9_TIMING_RUNS {
            let t0 = std::time::Instant::now();
            run_once(&mut session)?;
            micros.push(t0.elapsed().as_micros());
        }
        micros.sort_unstable();
        let p50 = micros[micros.len() / 2];
        let p95 = micros[micros.len() * 95 / 100];
        let (la, lb) = run_once(&mut session)?;
        Ok((la, lb, p50, p95))
    }

    /// Resolve the E9 model/sample pair: explicit env override, else the
    /// worktree-default experiment outputs.
    fn e9_paths(
        env_model: &str,
        default_file: &str,
    ) -> Option<(std::path::PathBuf, std::path::PathBuf)> {
        let out_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../../scripts/experiments/out/fire_model");
        let model = match std::env::var(env_model) {
            Ok(p) => std::path::PathBuf::from(p),
            Err(_) => out_dir.join(default_file),
        };
        let sample = std::env::var("WOWSP_TEST_SAMPLE")
            .map(std::path::PathBuf::from)
            .unwrap_or_else(|_| out_dir.join("sample_input.json"));
        model.is_file().then_some((model, sample))
    }

    /// fp32 delivery: the PyTorch-exported `fp32.onnx` loads into the ort
    /// build and answers a real featurized tick.
    #[test]
    #[ignore = "needs the trained model from scripts/experiments/train_fire_model.py"]
    fn e9_real_model_forward_fp32() {
        let Some((model, sample)) = e9_paths("WOWSP_TEST_MODEL", "fp32.onnx") else {
            eprintln!("[e9] fp32.onnx not found (train with train_fire_model.py) - skipping");
            return;
        };
        let (la, lb, p50, p95) = e9_run_real_model(&model, &sample).expect("real model forward");
        eprintln!(
            "[e9] fp32 model {} loaded; logits A {la:.4} B {lb:.4}; latency p50 {p50} us / p95 {p95} us over {E9_TIMING_RUNS} runs",
            model.display()
        );
    }

    /// int8 delivery: the dynamically-quantized `int8.onnx` (MatMul weights
    /// int8, activations fp32) loads and answers the same tick — the
    /// ship-this-size variant.
    #[test]
    #[ignore = "needs the trained model from scripts/experiments/train_fire_model.py"]
    fn e9_real_model_forward_int8() {
        let Some((model, sample)) = e9_paths("WOWSP_TEST_MODEL_INT8", "int8.onnx") else {
            eprintln!("[e9] int8.onnx not found (train with train_fire_model.py) - skipping");
            return;
        };
        let (la, lb, p50, p95) = e9_run_real_model(&model, &sample).expect("real int8 forward");
        eprintln!(
            "[e9] int8 model {} loaded; logits A {la:.4} B {lb:.4}; latency p50 {p50} us / p95 {p95} us over {E9_TIMING_RUNS} runs",
            model.display()
        );
    }
}
