//! Decision-AI feasibility shell (experiment E1).
//!
//! Proves the full inference chain the built-in decision model will need:
//! `ort` statically links ONNX Runtime into the binary, a tiny fixture model
//! (embedded at compile time via `include_bytes!` — no runtime file access,
//! no network) loads into a lazily-created [`Session`], and a real forward
//! pass is served over Tauri IPC.
//!
//! The fixture is a single MatMul over float32[1,8]: `y = x @ W` with
//! `W[i][j] = 2.0` when `i == j` else `0.5`, i.e. `y[i] = 1.5*x[i] +
//! 0.5*sum(x)`. The output-to-suggestion mapping (`heading_sector` /
//! `speed_setting` / `fire`) is placeholder semantics chosen to exercise
//! argmax / threshold paths, not tactical advice — the real model replaces
//! both the weights and the head layout later.
//!
//! Concurrency: `Session::run` takes `&mut self` in this `ort` line (ONNX
//! Runtime internals are not thread-safe), so the fixture session lives in a
//! [`Mutex`] behind a [`OnceLock`] — created once per process, inference
//! serialized. Fine for an E1 shell; a real model will shard per-thread
//! sessions or batch requests.

use std::sync::{Mutex, OnceLock};

use ort::{session::Session, value::Tensor};
use wowsp_tauri_shared::{DecisionAiStatus, DecisionDummyState, DecisionDummySuggestion};

/// The `ort` crate pin from the root Cargo.toml. Dependency versions are not
/// exposed through `env!` at compile time and ort publishes no public
/// version constant, so this is synced manually — the test below only echoes
/// it, it cannot detect drift.
const ORT_CRATE_VERSION: &str = "2.0.0-rc.13";

/// Fixture model bytes: the ONNX graph described in the module docs (369
/// bytes on disk). Generated by a one-off Python `onnx` script during
/// experiment E1; regenerate only with a matching expected-output update in
/// the tests below.
const FIXTURE_MODEL: &[u8] = include_bytes!("fixtures/decision_ai_tiny.onnx");

/// Fixture input width — also the output width (single MatMul). Tied to the
/// 8 fields of [`DecisionDummyState`].
const STATE_DIM: usize = 8;

static FIXTURE_SESSION: OnceLock<Result<Mutex<Session>, String>> = OnceLock::new();

/// Build a session from raw ONNX bytes. Isolated so tests can spin up their
/// own session instead of going through the process-global fixture.
/// (`commit_from_memory` — this ort RC renamed the rc.9-era
/// `commit_from_bytes`.)
fn session_from_bytes(bytes: &[u8]) -> Result<Session, String> {
    let mut builder = Session::builder().map_err(|e| format!("create session builder: {e}"))?;
    builder
        .commit_from_memory(bytes)
        .map_err(|e| format!("load ONNX model: {e}"))
}

/// The process-global fixture session, created on first use.
fn fixture_session() -> Result<&'static Mutex<Session>, String> {
    FIXTURE_SESSION
        .get_or_init(|| session_from_bytes(FIXTURE_MODEL).map(Mutex::new))
        .as_ref()
        .map_err(Clone::clone)
}

/// Flatten the dummy state into the model's input row, in
/// [`DecisionDummyState`] field order.
fn state_to_input(state: &DecisionDummyState) -> [f32; STATE_DIM] {
    [
        state.own_heading_sin,
        state.own_heading_cos,
        state.own_speed,
        state.enemy_bearing_sin,
        state.enemy_bearing_cos,
        state.enemy_distance,
        state.own_hp_fraction,
        state.target_visible,
    ]
}

/// Run one forward pass of `session` and return the flat output row.
/// Shape-checked: the fixture must answer float32[1, STATE_DIM].
fn forward(session: &mut Session, input: &[f32; STATE_DIM]) -> Result<[f32; STATE_DIM], String> {
    let tensor = Tensor::from_array(([1usize, STATE_DIM], input.to_vec()))
        .map_err(|e| format!("build input tensor: {e}"))?;
    let outputs = session
        .run(ort::inputs!["x" => tensor])
        .map_err(|e| format!("run inference: {e}"))?;
    let view = outputs["y"]
        .try_extract_array::<f32>()
        .map_err(|e| format!("extract output: {e}"))?;
    if view.shape() != [1, STATE_DIM].as_slice() {
        return Err(format!(
            "unexpected output shape {:?}, expected [1, {STATE_DIM}]",
            view.shape()
        ));
    }
    let flat: Vec<f32> = view.iter().copied().collect();
    flat.try_into()
        .map_err(|v: Vec<f32>| format!("expected {STATE_DIM} outputs, got {}", v.len()))
}

/// Index of the largest element (first one on ties — deterministic).
fn argmax(xs: &[f32]) -> usize {
    let mut best = 0;
    for (i, x) in xs.iter().enumerate() {
        if *x > xs[best] {
            best = i;
        }
    }
    best
}

/// Map the fixture model's 8 output logits to the dummy suggestion. A pure
/// function so tests can drive it without a session:
///   logits 0..4 → heading sector (argmax, 0-3)
///   logits 4..7 → throttle level (argmax, 0-2)
///   logit 7     → fire vote (> 0)
fn map_logits(y: &[f32; STATE_DIM]) -> DecisionDummySuggestion {
    DecisionDummySuggestion {
        heading_sector: argmax(&y[0..4]) as u32,
        speed_setting: argmax(&y[4..7]) as u32,
        fire: y[STATE_DIM - 1] > 0.0,
    }
}

/// Decision-AI runtime status: `ort` crate version, native ONNX Runtime
/// build info, and whether the embedded fixture loaded into a live session.
#[tauri::command]
pub fn decision_ai_status() -> Result<DecisionAiStatus, String> {
    Ok(DecisionAiStatus {
        ort_version: ORT_CRATE_VERSION.to_string(),
        runtime_info: ort::info().to_string(),
        fixture_loaded: fixture_session().is_ok(),
    })
}

/// One forward pass of the fixture model over a dummy battle state — the
/// end-to-end E1 chain: embedded bytes → session → inference → suggestion.
#[tauri::command]
pub fn decision_ai_suggest(state: DecisionDummyState) -> Result<DecisionDummySuggestion, String> {
    let input = state_to_input(&state);
    let session = fixture_session()?;
    let mut session = session
        .lock()
        .map_err(|_| "fixture session mutex poisoned")?;
    let y = forward(&mut session, &input)?;
    Ok(map_logits(&y))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Reference output for input [1..8]: `y[i] = 1.5*x[i] + 0.5*sum(x)` =
    /// `1.5*x[i] + 18`. All values are dyadic rationals well inside f32's
    /// exact-integer/half range, so every intermediate of the MatMul is
    /// exactly representable and exact equality is meaningful.
    const EXPECTED_Y: [f32; STATE_DIM] = [19.5, 21.0, 22.5, 24.0, 25.5, 27.0, 28.5, 30.0];

    /// Load the embedded fixture → session → one forward pass → assert the
    /// output shape AND the exact expected values.
    #[test]
    fn fixture_forward_matches_reference() {
        let mut session = session_from_bytes(FIXTURE_MODEL).expect("load fixture session");
        let input = [1.0f32, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0];
        let tensor =
            Tensor::from_array(([1usize, STATE_DIM], input.to_vec())).expect("build input tensor");
        let outputs = session
            .run(ort::inputs!["x" => tensor])
            .expect("run inference");
        let y = outputs["y"]
            .try_extract_array::<f32>()
            .expect("extract output");
        assert_eq!(y.shape(), &[1, STATE_DIM]);
        let got: Vec<f32> = y.iter().copied().collect();
        assert_eq!(got.as_slice(), EXPECTED_Y);
    }

    /// The command path through the process-global session produces the
    /// analytically-derived suggestion for a crafted state:
    /// x = [0, 1, 0.5, -1, 0, 1, 1, 1] → sum = 3.5 → y[i] = 1.5*x[i] + 1.75
    ///   = [1.75, 3.25, 2.5, 0.25, 1.75, 3.25, 3.25, 3.25]
    /// argmax(y[0..4]) = 1, argmax(y[4..7]) = 1 (first of the 3.25 tie),
    /// y[7] > 0 → fire.
    #[test]
    fn suggest_runs_the_full_chain() {
        let state = DecisionDummyState {
            own_heading_sin: 0.0,
            own_heading_cos: 1.0,
            own_speed: 0.5,
            enemy_bearing_sin: -1.0,
            enemy_bearing_cos: 0.0,
            enemy_distance: 1.0,
            own_hp_fraction: 1.0,
            target_visible: 1.0,
        };
        let suggestion = decision_ai_suggest(state).expect("suggest");
        assert_eq!(
            suggestion,
            DecisionDummySuggestion {
                heading_sector: 1,
                speed_setting: 1,
                fire: true,
            }
        );
    }

    /// The logit mapping is a pure function — drive it directly with
    /// hand-picked logits, including the fire threshold at exactly 0.
    #[test]
    fn map_logits_picks_sector_speed_and_fire() {
        let s = map_logits(&[0.1, 0.2, 3.0, -1.0, 0.0, 2.5, 1.0, 0.25]);
        assert_eq!(s.heading_sector, 2);
        assert_eq!(s.speed_setting, 1);
        assert!(s.fire);

        // Sector 0 / speed 0 lead from the front; zero logit does not fire.
        let s = map_logits(&[5.0, 1.0, 0.0, 0.0, 9.0, 1.0, 2.0, 0.0]);
        assert_eq!(s.heading_sector, 0);
        assert_eq!(s.speed_setting, 0);
        assert!(!s.fire);

        let s = map_logits(&[-5.0, -1.0, -0.1, -9.0, -9.0, -0.5, -1.0, -3.0]);
        assert_eq!(s.heading_sector, 2);
        assert_eq!(s.speed_setting, 1);
        assert!(!s.fire);
    }

    /// Status reports the pinned ort version and a live fixture session.
    #[test]
    fn status_reports_loaded_fixture() {
        let status = decision_ai_status().expect("status");
        assert_eq!(status.ort_version, ORT_CRATE_VERSION);
        assert!(status.fixture_loaded);
        assert!(!status.runtime_info.is_empty());
    }

    // ── E9 step 3: load the REAL trained model through ort ──────────────────
    //
    // The E1 fixture above proves the runtime; these tests prove the rest of
    // the delivery loop: a model actually TRAINED by
    // `scripts/experiments/train_fire_model.py` (PyTorch → static-shape ONNX,
    // optional int8 dynamic quantization) loads into the same `ort` build and
    // answers a forward pass on a REAL featurized tick (the JSONL export of
    // E9 step 1, featurized by the training script into `sample_input.json`).
    // Both tests default to the worktree's experiment output directory and
    // skip when the files are absent; run explicitly with
    // `cargo test -p wowsp_tauri e9_real_model -- --ignored --nocapture`.

    /// Model input geometry — must mirror the training script's export
    /// (entity [1, 24, 10], global_feat [1, 14], mask [1, 24]).
    const E9_SLOTS: usize = 24;
    const E9_ENTITY_DIM: usize = 10;
    const E9_GLOBAL_DIM: usize = 14;
    /// Forward passes timed for the latency report (after 5 warmups).
    const E9_TIMING_RUNS: usize = 50;

    /// Load + forward one real model, asserting the output contract and
    /// reporting latency. Returns (logit_a, logit_b, p50_us, p95_us).
    fn e9_run_real_model(
        model_path: &std::path::Path,
        sample_path: &std::path::Path,
    ) -> Result<(f32, f32, u128, u128), String> {
        let bytes = std::fs::read(model_path).map_err(|e| format!("read model: {e}"))?;
        let mut session = session_from_bytes(&bytes)?;
        let sample: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(sample_path).map_err(|e| {
                format!(
                    "read {} (regenerate via train_fire_model.py): {e}",
                    sample_path.display()
                )
            })?)
            .map_err(|e| format!("parse sample_input.json: {e}"))?;
        let nums = |key: &str, want: usize| -> Result<Vec<f32>, String> {
            serde_json::from_value::<Vec<f32>>(sample[key].clone())
                .map_err(|e| format!("parse sample '{key}' as f32 array: {e}"))
                .and_then(|v| {
                    if v.len() == want {
                        Ok(v)
                    } else {
                        Err(format!(
                            "sample '{key}' has {} entries, expected {want}",
                            v.len()
                        ))
                    }
                })
        };
        // entity is serialized nested [SLOTS][ENTITY_DIM] (self-documenting);
        // global/mask are flat.
        let entity: Vec<f32> = serde_json::from_value::<Vec<Vec<f32>>>(sample["entity"].clone())
            .map_err(|e| format!("parse sample 'entity' as f32 matrix: {e}"))
            .and_then(|rows| {
                if rows.len() == E9_SLOTS && rows.iter().all(|r| r.len() == E9_ENTITY_DIM) {
                    Ok(rows.into_iter().flatten().collect())
                } else {
                    Err(format!(
                        "sample 'entity' is not [{E9_SLOTS}][{E9_ENTITY_DIM}]"
                    ))
                }
            })?;
        let global = nums("global", E9_GLOBAL_DIM)?;
        let mask = nums("mask", E9_SLOTS)?;
        let entity_t = ort::value::Tensor::from_array(([1usize, E9_SLOTS, E9_ENTITY_DIM], entity))
            .map_err(|e| format!("build entity tensor: {e}"))?;
        let global_t = ort::value::Tensor::from_array(([1usize, E9_GLOBAL_DIM], global))
            .map_err(|e| format!("build global tensor: {e}"))?;
        let mask_t = ort::value::Tensor::from_array(([1usize, E9_SLOTS], mask))
            .map_err(|e| format!("build mask tensor: {e}"))?;
        let run_once = |session: &mut Session| -> Result<(f32, f32), String> {
            let outputs = session
                .run(ort::inputs![
                    "entity" => entity_t.view(),
                    "global_feat" => global_t.view(),
                    "mask" => mask_t.view(),
                ])
                .map_err(|e| format!("run inference: {e}"))?;
            let mut logits = [0.0f32; 2];
            for (idx, name) in ["logitA", "logitB"].iter().enumerate() {
                let v = outputs
                    .get(name)
                    .ok_or_else(|| format!("output '{name}' missing"))?;
                let view = v
                    .try_extract_array::<f32>()
                    .map_err(|e| format!("extract {name}: {e}"))?;
                let flat: Vec<f32> = view.iter().copied().collect();
                // The exported heads squeeze to [1]; accept [1] or [1,1].
                assert_eq!(flat.len(), 1, "output {name} shape {:?}", view.shape());
                assert!(
                    flat[0].is_finite(),
                    "output {name} is not finite: {}",
                    flat[0]
                );
                logits[idx] = flat[0];
            }
            Ok((logits[0], logits[1]))
        };
        // Warmup, then timed forwards (single-threaded session use, mirroring
        // how a real tick-time suggestion would run).
        for _ in 0..5 {
            run_once(&mut session)?;
        }
        let mut micros: Vec<u128> = Vec::with_capacity(E9_TIMING_RUNS);
        for _ in 0..E9_TIMING_RUNS {
            let t0 = std::time::Instant::now();
            run_once(&mut session)?;
            micros.push(t0.elapsed().as_micros());
        }
        micros.sort_unstable();
        let p50 = micros[micros.len() / 2];
        let p95 = micros[micros.len() * 95 / 100];
        let (la, lb) = run_once(&mut session)?;
        Ok((la, lb, p50, p95))
    }

    /// Resolve the E9 model/sample pair: explicit env override, else the
    /// worktree-default experiment outputs.
    fn e9_paths(
        env_model: &str,
        default_file: &str,
    ) -> Option<(std::path::PathBuf, std::path::PathBuf)> {
        let out_dir = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../../scripts/experiments/out/fire_model");
        let model = match std::env::var(env_model) {
            Ok(p) => std::path::PathBuf::from(p),
            Err(_) => out_dir.join(default_file),
        };
        let sample = std::env::var("WOWSP_TEST_SAMPLE")
            .map(std::path::PathBuf::from)
            .unwrap_or_else(|_| out_dir.join("sample_input.json"));
        model.is_file().then_some((model, sample))
    }

    /// fp32 delivery: the PyTorch-exported `fp32.onnx` loads into the ort
    /// build and answers a real featurized tick.
    #[test]
    #[ignore = "needs the trained model from scripts/experiments/train_fire_model.py"]
    fn e9_real_model_forward_fp32() {
        let Some((model, sample)) = e9_paths("WOWSP_TEST_MODEL", "fp32.onnx") else {
            eprintln!("[e9] fp32.onnx not found (train with train_fire_model.py) - skipping");
            return;
        };
        let (la, lb, p50, p95) = e9_run_real_model(&model, &sample).expect("real model forward");
        eprintln!(
            "[e9] fp32 model {} loaded; logits A {la:.4} B {lb:.4}; latency p50 {p50} us / p95 {p95} us over {E9_TIMING_RUNS} runs",
            model.display()
        );
    }

    /// int8 delivery: the dynamically-quantized `int8.onnx` (MatMul weights
    /// int8, activations fp32) loads and answers the same tick — the
    /// ship-this-size variant.
    #[test]
    #[ignore = "needs the trained model from scripts/experiments/train_fire_model.py"]
    fn e9_real_model_forward_int8() {
        let Some((model, sample)) = e9_paths("WOWSP_TEST_MODEL_INT8", "int8.onnx") else {
            eprintln!("[e9] int8.onnx not found (train with train_fire_model.py) - skipping");
            return;
        };
        let (la, lb, p50, p95) = e9_run_real_model(&model, &sample).expect("real int8 forward");
        eprintln!(
            "[e9] int8 model {} loaded; logits A {la:.4} B {lb:.4}; latency p50 {p50} us / p95 {p95} us over {E9_TIMING_RUNS} runs",
            model.display()
        );
    }
}
