//! AUTO-GENERATED by `scripts/gen_method_tables.py` — do not edit by hand.
//!
//! Per-game-version ids of the Avatar/Vehicle client methods the replay
//! decoder consumes. The wire id in EntityMethod (0x08) packets is the
//! method's index in the entity's client-method table sorted by wire size
//! (BigWorld exposed index; stable sort — equal sizes keep XML order). The
//! mapping drifts every game version; see the generator's docstring for the
//! source of truth (replay_unpack entity definitions).

/// The method ids one game version's entity definitions resolve to.
#[derive(Debug, Clone, Copy)]
pub struct MethodIds {
    pub avatar_receive_artillery_shots: i32,
    pub avatar_receive_torpedoes: i32,
    pub avatar_receive_explosions: i32,
    pub avatar_receive_torpedo_direction: i32,
    pub avatar_receive_add_squadron: i32,
    pub avatar_receive_update_squadron: i32,
    pub avatar_receive_add_minimap_squadron: i32,
    pub avatar_receive_update_minimap_squadron: i32,
    pub avatar_receive_remove_minimap_squadron: i32,
    pub avatar_receive_ward_added: i32,
    pub avatar_receive_ward_removed: i32,
    pub avatar_receive_shot_kills: i32,
    /// Server-authoritative cumulative damage stats (receiveDamageStat).
    /// `None` for versions whose exposed id hasn't been pinned yet — the
    /// decoder then leaves the stream empty and the frontend falls back to
    /// its HP-delta heuristic.
    pub avatar_receive_damage_stat: Option<i32>,
}

/// (major, minor, patch) → ids, ascending. Produced from every version the
/// reference entity definitions ship.
pub static METHOD_TABLES: &[((u16, u16, u16), MethodIds)] = &[
    (
        (0, 11, 6),
        MethodIds {
            avatar_receive_artillery_shots: 107,
            avatar_receive_torpedoes: 108,
            avatar_receive_explosions: 110,
            avatar_receive_torpedo_direction: 100,
            avatar_receive_add_squadron: 101,
            avatar_receive_update_squadron: 122,
            avatar_receive_add_minimap_squadron: 94,
            avatar_receive_update_minimap_squadron: 86,
            avatar_receive_remove_minimap_squadron: 51,
            avatar_receive_ward_added: 99,
            avatar_receive_ward_removed: 53,
            avatar_receive_shot_kills: 109,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (0, 11, 7),
        MethodIds {
            avatar_receive_artillery_shots: 107,
            avatar_receive_torpedoes: 108,
            avatar_receive_explosions: 110,
            avatar_receive_torpedo_direction: 100,
            avatar_receive_add_squadron: 101,
            avatar_receive_update_squadron: 122,
            avatar_receive_add_minimap_squadron: 94,
            avatar_receive_update_minimap_squadron: 86,
            avatar_receive_remove_minimap_squadron: 51,
            avatar_receive_ward_added: 99,
            avatar_receive_ward_removed: 53,
            avatar_receive_shot_kills: 109,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (0, 11, 8),
        MethodIds {
            avatar_receive_artillery_shots: 105,
            avatar_receive_torpedoes: 106,
            avatar_receive_explosions: 108,
            avatar_receive_torpedo_direction: 97,
            avatar_receive_add_squadron: 99,
            avatar_receive_update_squadron: 120,
            avatar_receive_add_minimap_squadron: 89,
            avatar_receive_update_minimap_squadron: 81,
            avatar_receive_remove_minimap_squadron: 47,
            avatar_receive_ward_added: 96,
            avatar_receive_ward_removed: 49,
            avatar_receive_shot_kills: 107,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (0, 11, 9),
        MethodIds {
            avatar_receive_artillery_shots: 108,
            avatar_receive_torpedoes: 109,
            avatar_receive_explosions: 111,
            avatar_receive_torpedo_direction: 100,
            avatar_receive_add_squadron: 102,
            avatar_receive_update_squadron: 123,
            avatar_receive_add_minimap_squadron: 91,
            avatar_receive_update_minimap_squadron: 83,
            avatar_receive_remove_minimap_squadron: 47,
            avatar_receive_ward_added: 99,
            avatar_receive_ward_removed: 49,
            avatar_receive_shot_kills: 110,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (0, 11, 10),
        MethodIds {
            avatar_receive_artillery_shots: 108,
            avatar_receive_torpedoes: 109,
            avatar_receive_explosions: 111,
            avatar_receive_torpedo_direction: 100,
            avatar_receive_add_squadron: 102,
            avatar_receive_update_squadron: 123,
            avatar_receive_add_minimap_squadron: 91,
            avatar_receive_update_minimap_squadron: 83,
            avatar_receive_remove_minimap_squadron: 47,
            avatar_receive_ward_added: 99,
            avatar_receive_ward_removed: 49,
            avatar_receive_shot_kills: 110,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (0, 11, 11),
        MethodIds {
            avatar_receive_artillery_shots: 108,
            avatar_receive_torpedoes: 109,
            avatar_receive_explosions: 111,
            avatar_receive_torpedo_direction: 100,
            avatar_receive_add_squadron: 102,
            avatar_receive_update_squadron: 123,
            avatar_receive_add_minimap_squadron: 91,
            avatar_receive_update_minimap_squadron: 83,
            avatar_receive_remove_minimap_squadron: 47,
            avatar_receive_ward_added: 99,
            avatar_receive_ward_removed: 49,
            avatar_receive_shot_kills: 110,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 0, 0),
        MethodIds {
            avatar_receive_artillery_shots: 106,
            avatar_receive_torpedoes: 107,
            avatar_receive_explosions: 109,
            avatar_receive_torpedo_direction: 98,
            avatar_receive_add_squadron: 100,
            avatar_receive_update_squadron: 121,
            avatar_receive_add_minimap_squadron: 89,
            avatar_receive_update_minimap_squadron: 81,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 97,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 108,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 1, 0),
        MethodIds {
            avatar_receive_artillery_shots: 106,
            avatar_receive_torpedoes: 107,
            avatar_receive_explosions: 109,
            avatar_receive_torpedo_direction: 98,
            avatar_receive_add_squadron: 100,
            avatar_receive_update_squadron: 121,
            avatar_receive_add_minimap_squadron: 89,
            avatar_receive_update_minimap_squadron: 81,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 97,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 108,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 2, 0),
        MethodIds {
            avatar_receive_artillery_shots: 106,
            avatar_receive_torpedoes: 107,
            avatar_receive_explosions: 109,
            avatar_receive_torpedo_direction: 98,
            avatar_receive_add_squadron: 100,
            avatar_receive_update_squadron: 122,
            avatar_receive_add_minimap_squadron: 89,
            avatar_receive_update_minimap_squadron: 81,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 97,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 108,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 3, 1),
        MethodIds {
            avatar_receive_artillery_shots: 108,
            avatar_receive_torpedoes: 109,
            avatar_receive_explosions: 111,
            avatar_receive_torpedo_direction: 100,
            avatar_receive_add_squadron: 102,
            avatar_receive_update_squadron: 124,
            avatar_receive_add_minimap_squadron: 91,
            avatar_receive_update_minimap_squadron: 83,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 99,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 110,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 4, 0),
        MethodIds {
            avatar_receive_artillery_shots: 107,
            avatar_receive_torpedoes: 108,
            avatar_receive_explosions: 110,
            avatar_receive_torpedo_direction: 99,
            avatar_receive_add_squadron: 101,
            avatar_receive_update_squadron: 122,
            avatar_receive_add_minimap_squadron: 90,
            avatar_receive_update_minimap_squadron: 82,
            avatar_receive_remove_minimap_squadron: 45,
            avatar_receive_ward_added: 98,
            avatar_receive_ward_removed: 47,
            avatar_receive_shot_kills: 109,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 5, 0),
        MethodIds {
            avatar_receive_artillery_shots: 107,
            avatar_receive_torpedoes: 108,
            avatar_receive_explosions: 110,
            avatar_receive_torpedo_direction: 99,
            avatar_receive_add_squadron: 101,
            avatar_receive_update_squadron: 122,
            avatar_receive_add_minimap_squadron: 90,
            avatar_receive_update_minimap_squadron: 82,
            avatar_receive_remove_minimap_squadron: 45,
            avatar_receive_ward_added: 98,
            avatar_receive_ward_removed: 47,
            avatar_receive_shot_kills: 109,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 6, 0),
        MethodIds {
            avatar_receive_artillery_shots: 108,
            avatar_receive_torpedoes: 109,
            avatar_receive_explosions: 111,
            avatar_receive_torpedo_direction: 100,
            avatar_receive_add_squadron: 102,
            avatar_receive_update_squadron: 124,
            avatar_receive_add_minimap_squadron: 91,
            avatar_receive_update_minimap_squadron: 82,
            avatar_receive_remove_minimap_squadron: 45,
            avatar_receive_ward_added: 99,
            avatar_receive_ward_removed: 47,
            avatar_receive_shot_kills: 110,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 7, 0),
        MethodIds {
            avatar_receive_artillery_shots: 107,
            avatar_receive_torpedoes: 108,
            avatar_receive_explosions: 110,
            avatar_receive_torpedo_direction: 99,
            avatar_receive_add_squadron: 101,
            avatar_receive_update_squadron: 123,
            avatar_receive_add_minimap_squadron: 90,
            avatar_receive_update_minimap_squadron: 82,
            avatar_receive_remove_minimap_squadron: 45,
            avatar_receive_ward_added: 98,
            avatar_receive_ward_removed: 47,
            avatar_receive_shot_kills: 109,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 8, 0),
        MethodIds {
            avatar_receive_artillery_shots: 107,
            avatar_receive_torpedoes: 108,
            avatar_receive_explosions: 110,
            avatar_receive_torpedo_direction: 99,
            avatar_receive_add_squadron: 101,
            avatar_receive_update_squadron: 123,
            avatar_receive_add_minimap_squadron: 90,
            avatar_receive_update_minimap_squadron: 82,
            avatar_receive_remove_minimap_squadron: 45,
            avatar_receive_ward_added: 98,
            avatar_receive_ward_removed: 47,
            avatar_receive_shot_kills: 109,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 9, 0),
        MethodIds {
            avatar_receive_artillery_shots: 107,
            avatar_receive_torpedoes: 108,
            avatar_receive_explosions: 110,
            avatar_receive_torpedo_direction: 99,
            avatar_receive_add_squadron: 101,
            avatar_receive_update_squadron: 123,
            avatar_receive_add_minimap_squadron: 90,
            avatar_receive_update_minimap_squadron: 82,
            avatar_receive_remove_minimap_squadron: 45,
            avatar_receive_ward_added: 98,
            avatar_receive_ward_removed: 47,
            avatar_receive_shot_kills: 109,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 10, 0),
        MethodIds {
            avatar_receive_artillery_shots: 110,
            avatar_receive_torpedoes: 111,
            avatar_receive_explosions: 113,
            avatar_receive_torpedo_direction: 101,
            avatar_receive_add_squadron: 103,
            avatar_receive_update_squadron: 127,
            avatar_receive_add_minimap_squadron: 90,
            avatar_receive_update_minimap_squadron: 83,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 100,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 112,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (12, 11, 1),
        MethodIds {
            avatar_receive_artillery_shots: 111,
            avatar_receive_torpedoes: 112,
            avatar_receive_explosions: 114,
            avatar_receive_torpedo_direction: 102,
            avatar_receive_add_squadron: 104,
            avatar_receive_update_squadron: 128,
            avatar_receive_add_minimap_squadron: 91,
            avatar_receive_update_minimap_squadron: 84,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 101,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 113,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 0, 0),
        MethodIds {
            avatar_receive_artillery_shots: 111,
            avatar_receive_torpedoes: 112,
            avatar_receive_explosions: 114,
            avatar_receive_torpedo_direction: 102,
            avatar_receive_add_squadron: 104,
            avatar_receive_update_squadron: 128,
            avatar_receive_add_minimap_squadron: 91,
            avatar_receive_update_minimap_squadron: 84,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 101,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 113,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 0, 1),
        MethodIds {
            avatar_receive_artillery_shots: 111,
            avatar_receive_torpedoes: 112,
            avatar_receive_explosions: 114,
            avatar_receive_torpedo_direction: 102,
            avatar_receive_add_squadron: 104,
            avatar_receive_update_squadron: 128,
            avatar_receive_add_minimap_squadron: 91,
            avatar_receive_update_minimap_squadron: 84,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 101,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 113,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 1, 0),
        MethodIds {
            avatar_receive_artillery_shots: 111,
            avatar_receive_torpedoes: 112,
            avatar_receive_explosions: 114,
            avatar_receive_torpedo_direction: 102,
            avatar_receive_add_squadron: 104,
            avatar_receive_update_squadron: 128,
            avatar_receive_add_minimap_squadron: 91,
            avatar_receive_update_minimap_squadron: 84,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 101,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 113,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 2, 0),
        MethodIds {
            avatar_receive_artillery_shots: 112,
            avatar_receive_torpedoes: 113,
            avatar_receive_explosions: 115,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 105,
            avatar_receive_update_squadron: 129,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 114,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 3, 0),
        MethodIds {
            avatar_receive_artillery_shots: 112,
            avatar_receive_torpedoes: 113,
            avatar_receive_explosions: 115,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 105,
            avatar_receive_update_squadron: 129,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 114,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 4, 0),
        MethodIds {
            avatar_receive_artillery_shots: 112,
            avatar_receive_torpedoes: 113,
            avatar_receive_explosions: 115,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 105,
            avatar_receive_update_squadron: 129,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 114,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 5, 0),
        MethodIds {
            avatar_receive_artillery_shots: 112,
            avatar_receive_torpedoes: 113,
            avatar_receive_explosions: 115,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 105,
            avatar_receive_update_squadron: 129,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 114,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 5, 1),
        MethodIds {
            avatar_receive_artillery_shots: 112,
            avatar_receive_torpedoes: 113,
            avatar_receive_explosions: 115,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 105,
            avatar_receive_update_squadron: 129,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 114,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 6, 0),
        MethodIds {
            avatar_receive_artillery_shots: 112,
            avatar_receive_torpedoes: 113,
            avatar_receive_explosions: 115,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 105,
            avatar_receive_update_squadron: 129,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 114,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 6, 1),
        MethodIds {
            avatar_receive_artillery_shots: 112,
            avatar_receive_torpedoes: 113,
            avatar_receive_explosions: 115,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 105,
            avatar_receive_update_squadron: 129,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 114,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 7, 0),
        MethodIds {
            avatar_receive_artillery_shots: 112,
            avatar_receive_torpedoes: 113,
            avatar_receive_explosions: 115,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 105,
            avatar_receive_update_squadron: 129,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 114,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 8, 0),
        MethodIds {
            avatar_receive_artillery_shots: 112,
            avatar_receive_torpedoes: 113,
            avatar_receive_explosions: 115,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 105,
            avatar_receive_update_squadron: 129,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 114,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 9, 0),
        MethodIds {
            avatar_receive_artillery_shots: 112,
            avatar_receive_torpedoes: 113,
            avatar_receive_explosions: 115,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 105,
            avatar_receive_update_squadron: 129,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 114,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 10, 0),
        MethodIds {
            avatar_receive_artillery_shots: 114,
            avatar_receive_torpedoes: 115,
            avatar_receive_explosions: 118,
            avatar_receive_torpedo_direction: 104,
            avatar_receive_add_squadron: 107,
            avatar_receive_update_squadron: 132,
            avatar_receive_add_minimap_squadron: 93,
            avatar_receive_update_minimap_squadron: 86,
            avatar_receive_remove_minimap_squadron: 47,
            avatar_receive_ward_added: 103,
            avatar_receive_ward_removed: 49,
            avatar_receive_shot_kills: 117,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (13, 11, 0),
        MethodIds {
            avatar_receive_artillery_shots: 114,
            avatar_receive_torpedoes: 115,
            avatar_receive_explosions: 118,
            avatar_receive_torpedo_direction: 104,
            avatar_receive_add_squadron: 107,
            avatar_receive_update_squadron: 132,
            avatar_receive_add_minimap_squadron: 93,
            avatar_receive_update_minimap_squadron: 86,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 103,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 117,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 0, 0),
        MethodIds {
            avatar_receive_artillery_shots: 114,
            avatar_receive_torpedoes: 115,
            avatar_receive_explosions: 118,
            avatar_receive_torpedo_direction: 104,
            avatar_receive_add_squadron: 107,
            avatar_receive_update_squadron: 132,
            avatar_receive_add_minimap_squadron: 93,
            avatar_receive_update_minimap_squadron: 86,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 103,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 117,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 1, 0),
        MethodIds {
            avatar_receive_artillery_shots: 114,
            avatar_receive_torpedoes: 115,
            avatar_receive_explosions: 118,
            avatar_receive_torpedo_direction: 104,
            avatar_receive_add_squadron: 107,
            avatar_receive_update_squadron: 132,
            avatar_receive_add_minimap_squadron: 93,
            avatar_receive_update_minimap_squadron: 86,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 103,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 117,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 2, 0),
        MethodIds {
            avatar_receive_artillery_shots: 114,
            avatar_receive_torpedoes: 115,
            avatar_receive_explosions: 118,
            avatar_receive_torpedo_direction: 104,
            avatar_receive_add_squadron: 107,
            avatar_receive_update_squadron: 132,
            avatar_receive_add_minimap_squadron: 93,
            avatar_receive_update_minimap_squadron: 86,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 103,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 117,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 3, 0),
        MethodIds {
            avatar_receive_artillery_shots: 114,
            avatar_receive_torpedoes: 115,
            avatar_receive_explosions: 118,
            avatar_receive_torpedo_direction: 104,
            avatar_receive_add_squadron: 107,
            avatar_receive_update_squadron: 132,
            avatar_receive_add_minimap_squadron: 93,
            avatar_receive_update_minimap_squadron: 86,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 103,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 117,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 4, 0),
        MethodIds {
            avatar_receive_artillery_shots: 115,
            avatar_receive_torpedoes: 116,
            avatar_receive_explosions: 119,
            avatar_receive_torpedo_direction: 105,
            avatar_receive_add_squadron: 108,
            avatar_receive_update_squadron: 133,
            avatar_receive_add_minimap_squadron: 94,
            avatar_receive_update_minimap_squadron: 87,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 104,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 118,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 5, 0),
        MethodIds {
            avatar_receive_artillery_shots: 114,
            avatar_receive_torpedoes: 115,
            avatar_receive_explosions: 118,
            avatar_receive_torpedo_direction: 104,
            avatar_receive_add_squadron: 107,
            avatar_receive_update_squadron: 132,
            avatar_receive_add_minimap_squadron: 93,
            avatar_receive_update_minimap_squadron: 86,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 103,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 117,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 6, 0),
        MethodIds {
            avatar_receive_artillery_shots: 114,
            avatar_receive_torpedoes: 115,
            avatar_receive_explosions: 118,
            avatar_receive_torpedo_direction: 104,
            avatar_receive_add_squadron: 107,
            avatar_receive_update_squadron: 132,
            avatar_receive_add_minimap_squadron: 93,
            avatar_receive_update_minimap_squadron: 86,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 103,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 117,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 7, 0),
        MethodIds {
            avatar_receive_artillery_shots: 113,
            avatar_receive_torpedoes: 114,
            avatar_receive_explosions: 117,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 106,
            avatar_receive_update_squadron: 131,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 116,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 7, 1),
        MethodIds {
            avatar_receive_artillery_shots: 113,
            avatar_receive_torpedoes: 114,
            avatar_receive_explosions: 117,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 106,
            avatar_receive_update_squadron: 131,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 116,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 8, 0),
        MethodIds {
            avatar_receive_artillery_shots: 113,
            avatar_receive_torpedoes: 114,
            avatar_receive_explosions: 117,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 106,
            avatar_receive_update_squadron: 131,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 116,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 9, 0),
        MethodIds {
            avatar_receive_artillery_shots: 113,
            avatar_receive_torpedoes: 114,
            avatar_receive_explosions: 117,
            avatar_receive_torpedo_direction: 103,
            avatar_receive_add_squadron: 106,
            avatar_receive_update_squadron: 131,
            avatar_receive_add_minimap_squadron: 92,
            avatar_receive_update_minimap_squadron: 85,
            avatar_receive_remove_minimap_squadron: 46,
            avatar_receive_ward_added: 102,
            avatar_receive_ward_removed: 48,
            avatar_receive_shot_kills: 116,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 10, 0),
        MethodIds {
            avatar_receive_artillery_shots: 119,
            avatar_receive_torpedoes: 120,
            avatar_receive_explosions: 125,
            avatar_receive_torpedo_direction: 108,
            avatar_receive_add_squadron: 112,
            avatar_receive_update_squadron: 139,
            avatar_receive_add_minimap_squadron: 96,
            avatar_receive_update_minimap_squadron: 88,
            avatar_receive_remove_minimap_squadron: 47,
            avatar_receive_ward_added: 107,
            avatar_receive_ward_removed: 49,
            avatar_receive_shot_kills: 124,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (14, 11, 0),
        MethodIds {
            avatar_receive_artillery_shots: 119,
            avatar_receive_torpedoes: 120,
            avatar_receive_explosions: 125,
            avatar_receive_torpedo_direction: 108,
            avatar_receive_add_squadron: 112,
            avatar_receive_update_squadron: 139,
            avatar_receive_add_minimap_squadron: 96,
            avatar_receive_update_minimap_squadron: 88,
            avatar_receive_remove_minimap_squadron: 47,
            avatar_receive_ward_added: 107,
            avatar_receive_ward_removed: 49,
            avatar_receive_shot_kills: 124,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (15, 0, 0),
        MethodIds {
            avatar_receive_artillery_shots: 119,
            avatar_receive_torpedoes: 120,
            avatar_receive_explosions: 125,
            avatar_receive_torpedo_direction: 108,
            avatar_receive_add_squadron: 112,
            avatar_receive_update_squadron: 139,
            avatar_receive_add_minimap_squadron: 96,
            avatar_receive_update_minimap_squadron: 88,
            avatar_receive_remove_minimap_squadron: 47,
            avatar_receive_ward_added: 107,
            avatar_receive_ward_removed: 49,
            avatar_receive_shot_kills: 124,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (15, 1, 0),
        MethodIds {
            avatar_receive_artillery_shots: 118,
            avatar_receive_torpedoes: 119,
            avatar_receive_explosions: 123,
            avatar_receive_torpedo_direction: 108,
            avatar_receive_add_squadron: 111,
            avatar_receive_update_squadron: 137,
            avatar_receive_add_minimap_squadron: 96,
            avatar_receive_update_minimap_squadron: 88,
            avatar_receive_remove_minimap_squadron: 47,
            avatar_receive_ward_added: 107,
            avatar_receive_ward_removed: 49,
            avatar_receive_shot_kills: 122,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (15, 2, 0),
        MethodIds {
            avatar_receive_artillery_shots: 120,
            avatar_receive_torpedoes: 121,
            avatar_receive_explosions: 125,
            avatar_receive_torpedo_direction: 111,
            avatar_receive_add_squadron: 139,
            avatar_receive_update_squadron: 140,
            avatar_receive_add_minimap_squadron: 99,
            avatar_receive_update_minimap_squadron: 91,
            avatar_receive_remove_minimap_squadron: 48,
            avatar_receive_ward_added: 110,
            avatar_receive_ward_removed: 50,
            avatar_receive_shot_kills: 124,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (15, 3, 0),
        MethodIds {
            avatar_receive_artillery_shots: 121,
            avatar_receive_torpedoes: 122,
            avatar_receive_explosions: 126,
            avatar_receive_torpedo_direction: 111,
            avatar_receive_add_squadron: 114,
            avatar_receive_update_squadron: 140,
            avatar_receive_add_minimap_squadron: 99,
            avatar_receive_update_minimap_squadron: 91,
            avatar_receive_remove_minimap_squadron: 49,
            avatar_receive_ward_added: 110,
            avatar_receive_ward_removed: 51,
            avatar_receive_shot_kills: 125,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (15, 4, 0),
        MethodIds {
            avatar_receive_artillery_shots: 121,
            avatar_receive_torpedoes: 122,
            avatar_receive_explosions: 126,
            avatar_receive_torpedo_direction: 111,
            avatar_receive_add_squadron: 114,
            avatar_receive_update_squadron: 140,
            avatar_receive_add_minimap_squadron: 99,
            avatar_receive_update_minimap_squadron: 91,
            avatar_receive_remove_minimap_squadron: 49,
            avatar_receive_ward_added: 110,
            avatar_receive_ward_removed: 51,
            avatar_receive_shot_kills: 125,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (15, 5, 0),
        MethodIds {
            avatar_receive_artillery_shots: 121,
            avatar_receive_torpedoes: 122,
            avatar_receive_explosions: 126,
            avatar_receive_torpedo_direction: 111,
            avatar_receive_add_squadron: 114,
            avatar_receive_update_squadron: 140,
            avatar_receive_add_minimap_squadron: 99,
            avatar_receive_update_minimap_squadron: 91,
            avatar_receive_remove_minimap_squadron: 49,
            avatar_receive_ward_added: 110,
            avatar_receive_ward_removed: 51,
            avatar_receive_shot_kills: 125,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (15, 6, 0),
        MethodIds {
            avatar_receive_artillery_shots: 121,
            avatar_receive_torpedoes: 122,
            avatar_receive_explosions: 126,
            avatar_receive_torpedo_direction: 111,
            avatar_receive_add_squadron: 114,
            avatar_receive_update_squadron: 140,
            avatar_receive_add_minimap_squadron: 99,
            avatar_receive_update_minimap_squadron: 91,
            avatar_receive_remove_minimap_squadron: 49,
            avatar_receive_ward_added: 110,
            avatar_receive_ward_removed: 51,
            avatar_receive_shot_kills: 125,
            avatar_receive_damage_stat: None,
        },
    ),
    (
        (15, 7, 0),
        MethodIds {
            avatar_receive_artillery_shots: 123,
            avatar_receive_torpedoes: 124,
            avatar_receive_explosions: 128,
            avatar_receive_torpedo_direction: 113,
            avatar_receive_add_squadron: 116,
            avatar_receive_update_squadron: 142,
            avatar_receive_add_minimap_squadron: 101,
            avatar_receive_update_minimap_squadron: 93,
            avatar_receive_remove_minimap_squadron: 49,
            avatar_receive_ward_added: 112,
            avatar_receive_ward_removed: 51,
            avatar_receive_shot_kills: 127,
            avatar_receive_damage_stat: None,
        },
    ),
    // 15.8.0 has no reference entity definitions yet — this row is derived
    // empirically from captured 15.8 replays (see `EMPIRICAL_OVERRIDES` in
    // scripts/gen_method_tables.py): three avatar methods inserted below the
    // battle-effect cluster shift it +3 (artillery 123→126, torpedoes
    // 124→127, shotKills 127→130, updateSquadron 142→145), while the
    // squadron add/minimap ids keep their 15.7 values; receiveDamageStat —
    // absent from every shipped def table so far — sits at 163.
    // E10 (2026-09-20): recomputed from the authoritative entity defs of
    // game build 13187581 — 13/13 anchors reproduce exactly after adopting
    // the two def-derived corrections (2026-09-21, user-approved decode
    // behaviour change): explosions=131 (the same +3 cluster shift as
    // artillery/torps/shotKills; 128 was the unshifted 15.7 carryover and
    // names updateMissileWaypoints) and wardRemoved=51 (id 50 is
    // receive_removeSquadron — it fires paired with
    // removeMinimapSquadron@49 on identical PLANE_IDs while wardAdded never
    // fires; the def-derived full table lives in the tests module with the
    // evidence).
    (
        (15, 8, 0),
        MethodIds {
            avatar_receive_artillery_shots: 126,
            avatar_receive_torpedoes: 127,
            avatar_receive_explosions: 131,
            avatar_receive_torpedo_direction: 113,
            avatar_receive_add_squadron: 116,
            avatar_receive_update_squadron: 145,
            avatar_receive_add_minimap_squadron: 101,
            avatar_receive_update_minimap_squadron: 93,
            avatar_receive_remove_minimap_squadron: 49,
            avatar_receive_ward_added: 112,
            avatar_receive_ward_removed: 51,
            avatar_receive_shot_kills: 130,
            avatar_receive_damage_stat: Some(163),
        },
    ),
];

/// Resolve the method-id table for a `clientVersionFromExe` descriptor value
/// (comma-separated `major,minor,patch[,build]`). Exact version first, else the
/// newest table not newer than the replay, else the oldest table (legacy
/// replays predate the shipped definitions) / newest table (replays from a
/// client newer than every shipped table — ids mostly append, so the newest
/// table is the best guess). `None` (no version string) assumes the newest.
pub fn method_ids_for_version(client_version: Option<&str>) -> &'static MethodIds {
    let key = client_version.and_then(parse_version_key);
    let idx = match key {
        Some(k) => {
            let mut chosen = 0usize;
            for (i, (v, _)) in METHOD_TABLES.iter().enumerate() {
                if *v <= k {
                    chosen = i;
                }
            }
            chosen
        },
        None => METHOD_TABLES.len() - 1,
    };
    &METHOD_TABLES[idx].1
}

/// `"15,0,0,11791718"` → `(15, 0, 0)`; malformed input yields `None`.
fn parse_version_key(v: &str) -> Option<(u16, u16, u16)> {
    let mut parts = v.split(',');
    let (Some(a), Some(b), Some(c)) = (parts.next(), parts.next(), parts.next()) else {
        return None;
    };
    Some((
        a.trim().parse().ok()?,
        b.trim().parse().ok()?,
        c.trim().parse().ok()?,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Version selection: exact, older-than-all, newer-than-all, malformed.
    #[test]
    fn selects_table_by_version() {
        // Newer than every shipped table falls back to the newest one.
        let newest = method_ids_for_version(Some("99,0,0,1"));
        let last = METHOD_TABLES[METHOD_TABLES.len() - 1].1;
        assert_eq!(
            newest.avatar_receive_explosions,
            last.avatar_receive_explosions
        );
        // Older than every shipped table falls back to the oldest one.
        let oldest = method_ids_for_version(Some("0,9,9,1"));
        let first = &METHOD_TABLES[0].1;
        assert_eq!(
            oldest.avatar_receive_artillery_shots,
            first.avatar_receive_artillery_shots
        );
        assert!(method_ids_for_version(None).avatar_receive_artillery_shots > 0);
        assert!(method_ids_for_version(Some("garbage")).avatar_receive_artillery_shots > 0);
    }

    /// Every table carries the ids the decoder needs (no -1 placeholders in the
    /// shipped versions — a -1 would silently disable that event stream).
    #[test]
    fn all_tables_fully_populated() {
        for (v, t) in METHOD_TABLES {
            for id in [
                t.avatar_receive_artillery_shots,
                t.avatar_receive_torpedoes,
                t.avatar_receive_explosions,
                t.avatar_receive_add_minimap_squadron,
                t.avatar_receive_update_minimap_squadron,
                t.avatar_receive_remove_minimap_squadron,
                t.avatar_receive_ward_added,
                t.avatar_receive_ward_removed,
                t.avatar_receive_shot_kills,
                t.avatar_receive_torpedo_direction,
                t.avatar_receive_add_squadron,
                t.avatar_receive_update_squadron,
            ] {
                assert!(id > 0, "unpopulated id in table {v:?}");
            }
        }
    }

    /// The complete 15.8.0 Avatar exposed-method table (E10): id -> name
    /// for all 180 client methods, recomputed from the entity defs of
    /// game build 13187581 (the exact build 15.8.0 replays record with)
    /// and wire-validated on a full-battle capture (100% of the 64
    /// distinct ids / 66,186 calls observed on avatar entities resolve).
    /// Research artifact for upcoming decoders — the packet decoder
    /// keeps reading the pinned row above.
    static AVATAR_METHODS_15_8_0: &[(i32, &str)] = &[
        (0, "commitStats"),
        (1, "onBattleEnd"),
        (2, "onBattleInterrupted"),
        (3, "onEndTerrainCollision"),
        (4, "onWorldStateReceived"),
        (5, "createDynamicDivision"),
        (6, "leaveDynamicDivision"),
        (7, "clearSubmarineHydrophone"),
        (8, "hideIntuitionIndicator"),
        (9, "hideHydrophoneIndicator"),
        (10, "vehicleLeaveSmoke"),
        (11, "notifyAboutSmokePenalty"),
        (12, "ownSmokeStartsFade"),
        (13, "capturedAsAGoal"),
        (14, "setIntuitionAngle"),
        (15, "setSubSkillAlert"),
        (16, "updateDetectionBySurfaceHydrophone"),
        (17, "diplomacyRejection"),
        (18, "onEvaluationAccepted"),
        (19, "updateMissileThreatStatus"),
        (20, "onLeaveDivision"),
        (21, "onConsumableModeChanged"),
        (22, "targetLoss"),
        (23, "receive_victoryPoints"),
        (24, "receiveShootDC"),
        (25, "onEndShipCollision"),
        (26, "artilleryAlert"),
        (27, "changePreBattleGrants"),
        (28, "onActionFailed"),
        (29, "startAppearing"),
        (30, "startDissapearing"),
        (31, "surfaceHydrophoneRemoveTarget"),
        (32, "ownSmokeCreated"),
        (33, "clientInsideSmoke"),
        (34, "updateBuoyancyRudderCruise"),
        (35, "onOwnerChanged"),
        (36, "onInviteRevoked"),
        (37, "onInviteRejected"),
        (38, "onInviteAccepted"),
        (39, "revokeInvite"),
        (40, "ownSmokeTimeLifeChanges"),
        (41, "onOilLeakStateChanged"),
        (42, "receiveTorpedoArmed"),
        (43, "receiveTorpedoSwitch"),
        (44, "receiveTorpedoSwitchAcoustic"),
        (45, "receiveTorpedoChasingSwitch"),
        (46, "torpedoParamsUpdate"),
        (47, "onSuccessiveTeamShots"),
        (48, "killMinefield"),
        (49, "receive_removeMinimapSquadron"),
        (50, "receive_removeSquadron"),
        (51, "receive_wardRemoved"),
        (52, "receive_startManeuvering"),
        (53, "receive_stopManeuvering"),
        (54, "receive_squadronOutOfFuel"),
        (55, "receive_dropJato"),
        (56, "onCheckGamePing"),
        (57, "onCheckCellPing"),
        (58, "onAchievementEarned"),
        (59, "receive_deactivateSquadron"),
        (60, "receive_squadronOutOfBounds"),
        (61, "receive_squadronNotify"),
        (62, "receive_changeThrottleMode"),
        (63, "receive_changeTurnMode"),
        (64, "receive_changeTurnDirection"),
        (65, "squadronConsumablePaused"),
        (66, "ownSquadronConsumableInterrupted"),
        (67, "squadronConsumableInterrupted"),
        (68, "squadronConsumableStopWorking"),
        (69, "receive_squadronInsideEnemyAura"),
        (70, "receive_squadronAuraThreatCount"),
        (71, "receive_squadronUnderFighterAttack"),
        (72, "receive_squadronUnderAimedFire"),
        (73, "receive_squadronChangeTeamAtMinimap"),
        (74, "receive_squadronChangeTeamAtWorld"),
        (75, "receive_fireExtinguishingStateChanged"),
        (76, "onShutdownTime"),
        (77, "deactivateAirSupport"),
        (78, "receive_changeState"),
        (79, "receive_squadronVisibilityChanged"),
        (80, "squadronConsumableSelected"),
        (81, "squadronConsumableEnabled"),
        (82, "receiveAcousticTargetID"),
        (83, "receiveVehicleDeath"),
        (84, "receive_squadronHealth"),
        (85, "receive_missileStateChanged"),
        (86, "receiveOilLeakPosition"),
        (87, "receive_squadronDamage"),
        (88, "beginOwnerlessTracers"),
        (89, "endOwnerlessTracers"),
        (90, "updateOwnerlessAuraState"),
        (91, "onMinimapAttention"),
        (92, "receiveMissileDamage"),
        (93, "receive_updateMinimapSquadron"),
        (94, "receive_squadronPlanesHealth"),
        (95, "onTerrainCollision"),
        (96, "updateOwnerlessTracersPosition"),
        (97, "receiveTorpedoSynchronization"),
        (98, "onShipCollision"),
        (99, "onDrawMinefieldPrediction"),
        (100, "receiveMissileKill"),
        (101, "receive_addMinimapSquadron"),
        (102, "drawDebugCross"),
        (103, "receive_teleportSquadron"),
        (104, "drawSphere"),
        (105, "receiveTorpedoManeuverEnd"),
        (106, "activateAirSupport"),
        (107, "drawDebugCircle"),
        (108, "receive_waterLaunchpadGenerated"),
        (109, "drawDebugLine"),
        (110, "drawCylinder"),
        (111, "drawCapsule"),
        (112, "receive_wardAdded"),
        (113, "receiveTorpedoDirection"),
        (114, "drawBoundingBox"),
        (115, "receiveMissile"),
        (116, "receive_addSquadron"),
        (117, "receiveSignedCommand"),
        (118, "receivePublicIntStat"),
        (119, "receivePublicFloatStat"),
        (120, "debugExec"),
        (121, "drawDebugLines"),
        (122, "onConnected"),
        (123, "receiveShellInfo"),
        (124, "onGameRoomStateChanged"),
        (125, "onNewPlayerSpawnedInBattle"),
        (126, "receiveArtilleryShots"),
        (127, "receiveTorpedoes"),
        (128, "updateMissileWaypoints"),
        (129, "resetMissileWaypoints"),
        (130, "receiveShotKills"),
        (131, "receiveExplosions"),
        (132, "receivePlaneProjectilePack"),
        (133, "receivePlaneSkipBombPacks"),
        (134, "receivePlaneRocketPacks"),
        (135, "receiveDepthChargesPacks"),
        (136, "receiveLaserBeams"),
        (137, "receiveSectorWaveShots"),
        (138, "receivePingerShots"),
        (139, "receivePingerShotKills"),
        (140, "addMinefield"),
        (141, "receiveMines"),
        (142, "receiveMineKills"),
        (143, "receiveProjectileTrace"),
        (144, "receiveDamageReport"),
        (145, "receive_updateSquadron"),
        (146, "receive_resetWaypoints"),
        (147, "receive_planeDeath"),
        (148, "receive_refresh"),
        (149, "squadronConsumableUsed"),
        (150, "receive_CommonCMD"),
        (151, "onChatMessage"),
        (152, "onDisconnectedFromServer"),
        (153, "onArenaStateReceived"),
        (154, "receiveChatHistory"),
        (155, "updateMinimapVisionInfo"),
        (156, "onBattleAchievementsRestored"),
        (157, "receiveAvatarInfo"),
        (158, "onEnterPreBattle"),
        (159, "receivePlayerData"),
        (160, "updatePreBattlesInfo"),
        (161, "onBuildingSpawned"),
        (162, "onBuildingsDataChanged"),
        (163, "receiveDamageStat"),
        (164, "inviteToPreBattle"),
        (165, "onInviteSent"),
        (166, "rejectInvite"),
        (167, "updateCoolDown"),
        (168, "updateSurfaceHydrophone"),
        (169, "updateSurfaceHydrophoneBroadcast"),
        (170, "increaseConsumablesCount"),
        (171, "increaseSquadronsConsumablesCount"),
        (172, "onPlaySound"),
        (173, "receiveScreenMessage"),
        (174, "receiveLowerLogMessage"),
        (175, "updateGameParams"),
        (176, "receiveOwnerlessBubbles"),
        (177, "onFeedback"),
        (178, "dev_receiveNavigationDebugData"),
        (179, "receivePingerLaunchPosition"),
    ];

    /// The complete 15.8.0 Vehicle exposed-method table, same provenance
    /// as AVATAR_METHODS_15_8_0 (84 methods; 100% of the 30 distinct ids
    /// / 11,178 calls observed on Vehicle entities resolve).
    static VEHICLE_METHODS_15_8_0: &[(i32, &str)] = &[
        (0, "makeShipCracksActive"),
        (1, "stopVarys"),
        (2, "forceReloadTorpedoes"),
        (3, "resetResettableWaveEnemyHits"),
        (4, "onNewWaveHornWave"),
        (5, "onCrashCrewEnable"),
        (6, "onCrashCrewDisable"),
        (7, "onCollisionWarningStateChanged"),
        (8, "syncTorpedoState"),
        (9, "useAntiMissile"),
        (10, "resetPinger"),
        (11, "onConsumableInterrupted"),
        (12, "onConsumablePaused"),
        (13, "stopFullScreenEffect"),
        (14, "onWeaponStateSwitched"),
        (15, "onConsumableSelected"),
        (16, "onConsumableEnabled"),
        (17, "onAirDefenseAimedFireStateChanged"),
        (18, "changeFireImmunity"),
        (19, "forceSink"),
        (20, "bodySinkPartLurched"),
        (21, "shootATBAGuns"),
        (22, "syncSurfacingTime"),
        (23, "receiveMirrorDamage"),
        (24, "onManualAirFireSet"),
        (25, "setNewSpeed"),
        (26, "useMissile"),
        (27, "shootOnClient"),
        (28, "chargeGuns"),
        (29, "stopShootingGuns"),
        (30, "shootWaveGun"),
        (31, "onPingDeactivated"),
        (32, "resetEnemyHit"),
        (33, "receiveHitLocationStateChange"),
        (34, "setAmmoForWeapon"),
        (35, "shootDepthCharge"),
        (36, "syncRageMode"),
        (37, "receivePingerShot"),
        (38, "onRespawned"),
        (39, "prepareChargeLaser"),
        (40, "updateWaveEnemyHit"),
        (41, "syncWaveGun"),
        (42, "teleport"),
        (43, "receiveUpdateAcousticHitFromEnemy"),
        (44, "drawSplash"),
        (45, "syncTorpedoTube"),
        (46, "drawDebugCross"),
        (47, "drawSphere"),
        (48, "shootTorpedo"),
        (49, "onPingerWaveEnemyHit"),
        (50, "drawDebugCircle"),
        (51, "receiveWaveFromEnemy"),
        (52, "drawDebugLine"),
        (53, "drawCylinder"),
        (54, "drawCapsule"),
        (55, "drawBoundingBox"),
        (56, "kill"),
        (57, "receiveBubbles"),
        (58, "debugExec"),
        (59, "drawDebugLines"),
        (60, "receiveSomeSplashInfo"),
        (61, "dev_receiveHitLocationDamage"),
        (62, "setTimesToBurn"),
        (63, "onPlayEffect"),
        (64, "onPlaySound"),
        (65, "addSubmarineHydrophoneTargets"),
        (66, "syncGun"),
        (67, "syncShipCracks"),
        (68, "setUniqueSkills"),
        (69, "setConsumables"),
        (70, "setSqsConsumables"),
        (71, "uniqueTriggerActivated"),
        (72, "onConsumableUsed"),
        (73, "setAirDefenseState"),
        (74, "receiveGunSyncRotations"),
        (75, "updateInvisibleWavedPoint"),
        (76, "receiveEnemyHitWaveDump"),
        (77, "setWildFireState"),
        (78, "reloadWeapon"),
        (79, "startFullScreenEffect"),
        (80, "receiveHitLocationsInitialState"),
        (81, "receiveDamagesOnShip"),
        (82, "syncShipPhysics"),
        (83, "setReloadingStateForWeapon"),
    ];

    /// Binary-search a 15.8.0 exposed table by method id.
    fn exposed_lookup(table: &'static [(i32, &'static str)], id: i32) -> Option<&'static str> {
        table
            .binary_search_by(|(i, _)| i.cmp(&id))
            .ok()
            .map(|idx| table[idx].1)
    }

    /// Look a 15.8.0 Avatar wire method id up in the exposed table.
    fn avatar_method_name_15_8_0(id: i32) -> Option<&'static str> {
        exposed_lookup(AVATAR_METHODS_15_8_0, id)
    }

    /// Look a 15.8.0 Vehicle wire method id up in the exposed table.
    fn vehicle_method_name_15_8_0(id: i32) -> Option<&'static str> {
        exposed_lookup(VEHICLE_METHODS_15_8_0, id)
    }

    /// The exposed tables are canonical: ids strictly ascending from 0 with
    /// no gaps, names unique.
    #[test]
    fn exposed_tables_15_8_have_canonical_shape() {
        for table in [AVATAR_METHODS_15_8_0, VEHICLE_METHODS_15_8_0] {
            assert!(!table.is_empty());
            assert_eq!(table[0].0, 0, "ids start at 0");
            for (i, (id, _)) in table.iter().enumerate() {
                assert_eq!(*id, i as i32, "ids are dense and ascending");
            }
            let mut names: Vec<&str> = table.iter().map(|(_, n)| *n).collect();
            names.sort_unstable();
            let dense = names.windows(2).all(|w| w[0] != w[1]);
            assert!(dense, "duplicate method names");
        }
    }

    /// The full 15.8.0 Avatar table agrees with the pinned 15.8.0 row on
    /// 11/13 ids; the two disagreements are the documented stale pins (see
    /// the row's comment): the defs (and the whole +3-shifted cluster around
    /// them) say explosions=131 and wardRemoved=51, while the row keeps the
    /// empirically-shipped 128 and 50. This test pins the residual in code —
    /// whoever resolves the two stale pins must update it deliberately.
    #[test]
    fn exposed_table_15_8_matches_pinned_row() {
        let row = method_ids_for_version(Some("15,8,0,13187581"));
        // The 11 verified pins resolve to the row's exact ids.
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_artillery_shots),
            Some("receiveArtilleryShots")
        );
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_torpedoes),
            Some("receiveTorpedoes")
        );
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_torpedo_direction),
            Some("receiveTorpedoDirection")
        );
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_add_squadron),
            Some("receive_addSquadron")
        );
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_update_squadron),
            Some("receive_updateSquadron")
        );
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_add_minimap_squadron),
            Some("receive_addMinimapSquadron")
        );
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_update_minimap_squadron),
            Some("receive_updateMinimapSquadron")
        );
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_remove_minimap_squadron),
            Some("receive_removeMinimapSquadron")
        );
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_ward_added),
            Some("receive_wardAdded")
        );
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_shot_kills),
            Some("receiveShotKills")
        );
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_damage_stat.unwrap()),
            Some("receiveDamageStat")
        );
        // The two former stale pins were adopted from the def-derived table
        // (2026-09-21, user-approved): explosions rides the +3 battle-effect
        // cluster shift at 131 (128 is updateMissileWaypoints), and
        // wardRemoved moved to 51 (50 is receive_removeSquadron, paired 1:1
        // with removeMinimapSquadron@49 on identical PLANE_IDs).
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_explosions),
            Some("receiveExplosions")
        );
        assert_eq!(
            avatar_method_name_15_8_0(row.avatar_receive_ward_removed),
            Some("receive_wardRemoved")
        );
    }

    /// E10 against the real replay (skips without `WOWSP_TEST_REPLAY`): every
    /// method id observed on Avatar (type 1) and Vehicle (type 2) entities
    /// must resolve to a name in the 15.8.0 exposed tables. On the reference
    /// capture both cover 100% of distinct ids (64 avatar, 30 vehicle).
    #[test]
    fn exposed_tables_cover_real_replay() {
        let Some(path) = std::env::var("WOWSP_TEST_REPLAY").ok() else {
            return;
        };
        let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
        let block_count = u32::from_le_bytes(bytes[4..8].try_into().unwrap()) as usize;
        let mut cur = 8;
        let mut client_version: Option<String> = None;
        for i in 0..block_count {
            let bl = u32::from_le_bytes(bytes[cur..cur + 4].try_into().unwrap()) as usize;
            cur += 4;
            if i == 0 {
                if let Ok(json) = serde_json::from_slice::<serde_json::Value>(&bytes[cur..cur + bl])
                {
                    client_version = json
                        .get("clientVersionFromExe")
                        .and_then(|x| x.as_str())
                        .map(str::to_string);
                }
            }
            cur += bl;
        }
        let decoded = crate::commands::packets::decode_replay(
            &bytes[cur..],
            &std::collections::HashSet::new(),
            client_version.as_deref(),
        )
        .expect("decode must succeed");
        // (entity_type -> method id -> calls) on the wire.
        let mut per_id: std::collections::BTreeMap<(i16, i32), u32> =
            std::collections::BTreeMap::new();
        for (_, eid, mid, _) in &decoded.method_histogram {
            let Some(et) = decoded.kinds.get(eid).map(|k| k.entity_type) else {
                continue;
            };
            *per_id.entry((et, *mid)).or_default() += 1;
        }
        let mut stats: std::collections::BTreeMap<i16, (usize, usize, usize, usize)> =
            std::collections::BTreeMap::new();
        for ((et, mid), n) in &per_id {
            let hit = match et {
                1 => avatar_method_name_15_8_0(*mid).is_some(),
                2 => vehicle_method_name_15_8_0(*mid).is_some(),
                _ => continue,
            };
            let e = stats.entry(*et).or_default();
            e.0 += 1;
            e.2 += *n as usize;
            if hit {
                e.1 += 1;
                e.3 += *n as usize;
            }
        }
        let is_15_8 = client_version.as_deref().and_then(parse_version_key) == Some((15, 8, 0));
        for (et, (distinct, resolved, calls, cov)) in stats {
            eprintln!(
                "[e10] type {et}: {resolved}/{distinct} distinct ids ({:.0}%), {cov}/{calls} calls ({:.0}%)",
                100.0 * resolved as f64 / distinct as f64,
                100.0 * cov as f64 / calls as f64,
            );
            if is_15_8 {
                assert!(
                    resolved * 20 >= distinct * 19,
                    "type {et}: only {resolved}/{distinct} ids resolve in the 15.8.0 tables"
                );
            }
        }
        let unresolved: Vec<String> = per_id
            .keys()
            .filter(|(et, mid)| match et {
                1 => avatar_method_name_15_8_0(*mid).is_none(),
                2 => vehicle_method_name_15_8_0(*mid).is_none(),
                _ => false,
            })
            .map(|(et, mid)| format!("type {et} id {mid}"))
            .collect();
        if !unresolved.is_empty() {
            eprintln!("[e10] unresolved: {}", unresolved.join(", "));
        }
    }
}
