/**
 * Map-version succession: which space ids are an OLD version of a map the
 * client still serves under a newer id.
 *
 * The client keeps retired spaces on disk (replays reference them for as
 * long as the server keeps old battles around), so the bundled catalog —
 * generated by walking an install's VFS — lists both generations of a
 * reworked map. Nothing in the data tells them apart: `37_Ridge` and
 * `58_RidgeNew` carry the SAME display name in every locale ("山脉锁链" /
 * "Mountain Range" / …), which is exactly why the rail needs this table.
 *
 * Entries are curated by hand from the id naming the client itself uses
 * (`*_new`, `*_RidgeNew`, …) plus an identical-name check across all
 * locales. Keep it small and evidenced: add an entry only when the old space
 * is demonstrably out of rotation (a reworked/superseded map), never for a
 * mere variant — winter/day skins such as `15_NE_north` /
 * `35_NE_north_winter` are two maps, not two versions of one.
 */

export interface LegacyMapInfo {
  /** Space id of the version still in rotation. */
  replacedBy: string;
  /** Why this pair is a version pair — the evidence, for the next editor. */
  evidence: string;
}

/** Old space id → its successor. */
export const LEGACY_MAP_VERSIONS: Readonly<Record<string, LegacyMapInfo>> = {
  "37_Ridge": {
    replacedBy: "58_RidgeNew",
    evidence:
      "Identical display names in all nine locales, and the successor's id carries the client's own `New` marker.",
  },
};

/** Lineage of a battle map: `legacy` for a superseded version, `current` for
 *  the space that replaced an older one, null for an unremarkable map. */
export type MapLineage = "legacy" | "current";

export function legacyMapOf(spaceId: string): LegacyMapInfo | null {
  return LEGACY_MAP_VERSIONS[spaceId] ?? null;
}

/** `legacy` when `spaceId` is superseded, `current` when it supersedes
 *  another space, null otherwise. Derived from one table, so the replacement
 *  is labelled by the same data that labels the original. */
export function mapLineage(spaceId: string): MapLineage | null {
  if (legacyMapOf(spaceId)) return "legacy";
  for (const info of Object.values(LEGACY_MAP_VERSIONS)) {
    if (info.replacedBy === spaceId) return "current";
  }
  return null;
}
