/**
 * Bundled authoritative ship rarity map.
 *
 * Generated by `scripts/model_convert/build_rarity_map.py` from an unpacked
 * `GameParams.json` (the `RarityCategory.name` field on each Ship entity).
 * Values are the official in-game bands: "Common" / "Uncommon" / "Rare" /
 * "Epic" / "Legendary".
 *
 * This ships with the app as a compact (~26KB) fallback so the rarity colour
 * is correct even when the user hasn't unpacked GameParams. Keys are the same
 * numeric ship_ids the WG encyclopedia returns (`GameParams.id == ship_id`).
 */
import rarityRaw from "@/data/ship_rarity.json";

const RARITY_BY_SHIP_ID = rarityRaw as Record<string, string>;

/** Look up the authoritative rarity band for a shipId, or null if absent. */
export function authoritativeRarity(shipId: number | undefined): string | null {
  if (shipId == null) return null;
  return RARITY_BY_SHIP_ID[String(shipId)] ?? null;
}
