/**
 * Lesta ship overlay (`src/data/ships_lesta.json`, generated by
 * `scripts/extract/build_lesta_overlay.py` from the Lesta client's decoded
 * GameParams and its text tables).
 *
 * The encyclopedia's primary source is the WG API, which knows nothing about
 * the research lines Lesta grew after the split (IJN CV line II, US BB line
 * IV, the Roman-emperor cruisers, …): those ships exist only in the Lesta
 * client files. This table carries exactly that gap — every Lesta tech-tree
 * ship with no WG-side entry — and the encyclopedia store appends the
 * missing entries while the ships view's branch source is set to Lesta, so
 * cards, click-through, specs and the build planner light up for them like
 * for any WG ship. Switching the branch source back to WG drops them again;
 * the merge never touches the WG API cache.
 *
 * Names: ru-RU from the Lesta client texts, en-US the GameParams working
 * name, the CJK trio (plus ja where established) hand-curated in
 * scripts/extract/lesta_names_curated.json — and the same ships also merge
 * into ship_names.json, so every offline-DB consumer (replay labels,
 * dashboards, name resolution) resolves them in any realm. The profile is
 * synthesized into the WG API's snake_case shape from the Lesta GameParams
 * top-hull sections (hull health, speed, concealment, artillery/torpedo
 * essentials).
 */
import type { ShipInfo } from "@/api";
import { useShipsUiStore } from "@/stores/shipsUi";

export interface LestaShipEntry {
  index: string;
  tier: number;
  type: string;
  nation: string;
  isPremium?: boolean;
  isSpecial?: boolean;
  /** Hand-curated / client-texts names keyed by canonical lang-loc. */
  names: Record<string, string>;
  /** Client-texts descriptions keyed by canonical lang-loc (ru-RU at least). */
  descriptions?: Record<string, string>;
  /** WG-API-shaped snake_case profile (synthesized from GameParams). */
  defaultProfile?: unknown;
}

export interface ShipsLestaOverlay {
  gameVersion: string;
  ships: Record<string, LestaShipEntry>;
}

let cache: Promise<ShipsLestaOverlay> | null = null;

/** Import (once) and keep the bundled Lesta overlay. Never rejects the call
 *  site's flow — `withLestaOverlay` degrades to the untouched list when the
 *  module is unavailable (an overlay-less lite build stays functional). */
export function loadShipsLesta(): Promise<ShipsLestaOverlay> {
  cache ??= import("@/data/ships_lesta.json").then(
    (m) => (m.default as ShipsLestaOverlay),
  );
  return cache;
}

/** Build a ShipInfo from an overlay entry, name picked for the requested
 *  language (canonical lang-loc → en-US → first available). */
export function lestaToShipInfo(
  shipId: number,
  overlay: ShipsLestaOverlay,
  entry: LestaShipEntry,
  lang: string,
): ShipInfo {
  const name =
    entry.names[lang] ?? entry.names["en-US"] ?? Object.values(entry.names)[0] ?? entry.index;
  return {
    shipId,
    name,
    tier: entry.tier,
    type: entry.type,
    nation: entry.nation,
    isPremium: !!entry.isPremium,
    isSpecial: !!entry.isSpecial,
    description: entry.descriptions?.[lang] ?? "",
    gameVersion: overlay.gameVersion,
    defaultProfile: entry.defaultProfile ?? null,
    // No WG CDN urls exist — empty strings hand resolution to the local
    // portrait PNG chain (res/images/ships/<shipId>.png).
    images: { small: "", medium: "", large: "", contour: "" },
  };
}

/** Append the Lesta-only ships to an encyclopedia list when the ships view's
 *  branch source is Lesta; the WG-sourced list is returned untouched
 *  otherwise (and when the overlay module fails to load). */
export async function withLestaOverlay(list: ShipInfo[], lang: string): Promise<ShipInfo[]> {
  if (useShipsUiStore().treeRealm !== "lesta") return list;
  let overlay: ShipsLestaOverlay;
  try {
    overlay = await loadShipsLesta();
  } catch {
    return list;
  }
  const have = new Set(list.map((s) => s.shipId));
  const extra: ShipInfo[] = [];
  for (const [id, entry] of Object.entries(overlay.ships)) {
    const shipId = Number(id);
    if (!Number.isFinite(shipId) || have.has(shipId)) continue;
    extra.push(lestaToShipInfo(shipId, overlay, entry, lang));
  }
  return extra.length ? [...list, ...extra] : list;
}
