/**
 * Bundled ship → event attribution map.
 *
 * Generated by `scripts/extract/build_event_map.py` from an unpacked
 * `GameParams.json` (the `peculiarity` field on each Ship entity, plus the
 * curated name/tag fallbacks for hulls the peculiarity system misses).
 * Keys are the numeric ship_ids the WG encyclopedia returns, joined through
 * wowsinfo.json's ship_id → index bridge — the same keying as
 * ship_rarity.json.
 *
 * Event ids resolve to their localized official names and first-appearance
 * versions through `utils/shipEvents.ts`; this module only answers "which
 * event, if any".
 */
import eventsRaw from "@/data/ship_events.json";

const EVENT_BY_SHIP_ID = eventsRaw as Record<string, string>;

/** Look up the event id for a shipId, or null when the ship is no event ship. */
export function authoritativeEvent(shipId: number | undefined): string | null {
  if (shipId == null) return null;
  return EVENT_BY_SHIP_ID[String(shipId)] ?? null;
}
