/**
 * Tests for the event-ship tag data chain:
 *  - ship_events.json (generated by scripts/extract/build_event_map.py),
 *    EVENT_META (utils/shipEvents.ts) and the i18n `ships.event` namespace
 *    must agree EXACTLY — a new event in the data without registry + locale
 *    entries (or a stale registry entry) fails here, so regeneration always
 *    comes with its curation;
 *  - shipRarity() must resolve event ships to the "event" tier regardless
 *    of their bundled RarityCategory band (event attribution wins);
 *  - the anchor ship ids pin the generated map's keying (WG ship_id, not
 *    GameParams.id): Smolensk_H2020 / ARP Kongō / Wukong.
 *
 * Locale files are imported directly (not through vue-i18n) — this is a
 * data-integrity test, label composition itself is a two-concat.
 */
import { describe, expect, it } from "vitest";

import eventsRaw from "@/data/ship_events.json";
import enShips from "../../../../res/i18n/locales/en-US/ships.json";
import zhShips from "../../../../res/i18n/locales/zh-CN/ships.json";
import { EVENT_META } from "./shipEvents";
import { shipRarity } from "./shipRarity";
import { authoritativeEvent } from "./shipEventData";

const EVENT_MAP = eventsRaw as Record<string, string>;

describe("event map integrity", () => {
  it("every mapped event has registry metadata and localized names", () => {
    const used = new Set(Object.values(EVENT_MAP));
    const registry = new Set(Object.keys(EVENT_META));
    expect([...used].filter((id) => !registry.has(id))).toEqual([]);
  });

  it("the registry carries no events absent from the data", () => {
    const used = new Set(Object.values(EVENT_MAP));
    const registry = new Set(Object.keys(EVENT_META));
    expect([...registry].filter((id) => !used.has(id))).toEqual([]);
  });

  it("every event has an official name in en-US and zh-CN", () => {
    const en = (enShips as { event?: Record<string, string> }).event ?? {};
    const zh = (zhShips as { event?: Record<string, string> }).event ?? {};
    for (const id of Object.keys(EVENT_META)) {
      expect(typeof en[id], `en-US name for ${id}`).toBe("string");
      expect(typeof zh[id], `zh-CN name for ${id}`).toBe("string");
      expect(zh[id]).not.toBe("");
    }
  });
});

describe("event rarity resolution", () => {
  it("resolves event ships to the event tier over their rarity band", () => {
    // Smolensk_H2020: bundled rarity "Common", event Halloween 2020.
    expect(
      shipRarity({ shipId: 4187927824, isPremium: false, isSpecial: true, tier: 10 }),
    ).toBe("event");
    expect(authoritativeEvent(4187927824)).toBe("halloween_2020");
  });

  it("pins the map keying with anchor ships", () => {
    expect(authoritativeEvent(4282267344)).toBeNull(); // Shimakaze — no event
    expect(EVENT_MAP["4187927824"]).toBe("halloween_2020"); // 狂风
  });

  it("leaves non-event ships on their rarity band", () => {
    expect(
      shipRarity({ shipId: 4074682352, isPremium: false, isSpecial: false, tier: 10 }),
    ).toBe("common"); // Worcester: tech tree
    expect(authoritativeEvent(undefined)).toBeNull();
    expect(authoritativeEvent(0)).toBeNull();
  });
});
