/**
 * Bundled tech-tree topologies, generated by `scripts/extract/build_techtree.py`.
 *
 * Two realm variants ship (the ships view's WG/Lesta switch picks one):
 *   - `tech_tree.json`   — the WG-cluster tree (wowsinfo bridge), the
 *     branch-structure reference; includes premium/special side leaves.
 *   - `tech_tree_lesta.json` — the Lesta tree, read straight from the
 *     game client's GameParams research graph (research lines only).
 *
 * Each node is keyed by shipId and carries the minimum the renderer needs:
 * tier, type, nation, rarity, archetype (branch flavour), and the shipIds it
 * unlocks. Premium/special ships that hang off a tech-tree node as a side
 * leaf are included with isPremium/isSpecial set (WG tree only).
 */
import treeWgRaw from "@/data/tech_tree.json";
import treeLestaRaw from "@/data/tech_tree_lesta.json";

export type TechTreeRealm = "wg" | "lesta";

export interface TechTreeNode {
  shipId: number;
  index: string;
  name: string;
  tier: number;
  type: string;
  nation: string;
  isPremium: boolean;
  isSpecial: boolean;
  rarity: string;
  archetype: string;
  nextShips: number[];
  group: string;
}

const TREES: Record<TechTreeRealm, Record<string, TechTreeNode>> = {
  wg: treeWgRaw as Record<string, TechTreeNode>,
  lesta: treeLestaRaw as Record<string, TechTreeNode>,
};

/** All tech-tree nodes of a realm, keyed by stringified shipId. */
export function allTechTreeNodes(realm: TechTreeRealm = "wg"): Record<string, TechTreeNode> {
  return TREES[realm];
}

/** One node by shipId in a realm, or null. */
export function techTreeNode(shipId: number, realm: TechTreeRealm = "wg"): TechTreeNode | null {
  return TREES[realm][String(shipId)] ?? null;
}

/**
 * Aliases resolving to the tree files' nation keys. WG's encyclopedia API
 * says "europe" while the game files say "pan_europe"; ship_names.json keeps
 * the raw game-file spellings "united_kingdom" and "russia". The WG API codes
 * uk/ussr are already the stored keys.
 */
const NATION_ALIASES: Record<string, string> = {
  europe: "pan_europe",
  united_kingdom: "uk",
  russia: "ussr",
};

/** Every node belonging to a nation in a realm. */
export function nationNodes(nation: string, realm: TechTreeRealm = "wg"): TechTreeNode[] {
  const key = NATION_ALIASES[nation] ?? nation;
  return Object.values(TREES[realm]).filter((n) => n.nation === key);
}

/**
 * Group a nation's nodes by ship type, each as a list of chains. A chain is a
 * root-to-leaf path through `nextShips` (a single branch). Forks (a node with
 * ≥2 children) spawn parallel chains so each sub-branch renders as its own
 * row of tiers. Side leaves (premium/special ships attached to a tree node)
 * are returned alongside the chain they hang off.
 */
export interface TechTreeBranch {
  /** shipIds along this branch, tier-ascending. */
  ships: number[];
  /** archetype code of the highest-tier ship in the branch (for labelling). */
  archetype: string;
}
export interface NationTree {
  type: string;
  branches: TechTreeBranch[];
}

export function nationTree(nation: string, realm: TechTreeRealm = "wg"): NationTree[] {
  const nodes = nationNodes(nation, realm);
  const byType: Record<string, TechTreeNode[]> = {};
  for (const n of nodes) (byType[n.type] ??= []).push(n);

  const out: NationTree[] = [];
  for (const [type, list] of Object.entries(byType)) {
    const byId = new Map(list.map((n) => [n.shipId, n]));
    // Roots: nodes nobody points to within this nation+type (tier-1 starters,
    // plus any orphans). A child is "pointed to" if some node lists it in
    // nextShips.
    const pointedTo = new Set<number>();
    for (const n of list) for (const nx of n.nextShips) if (byId.has(nx)) pointedTo.add(nx);
    const roots = list.filter((n) => !pointedTo.has(n.shipId)).sort((a, b) => a.tier - b.tier);

    const branches: TechTreeBranch[] = [];
    const walk = (start: TechTreeNode): void => {
      // DFS from root; each fork spawns a new branch.
      const stack: { node: TechTreeNode; path: number[] }[] = [{ node: start, path: [start.shipId] }];
      while (stack.length) {
        const { node, path } = stack.pop()!;
        const kids = node.nextShips.map((id) => byId.get(id)).filter((n): n is TechTreeNode => !!n);
        if (kids.length === 0) {
          const tip = byId.get(path[path.length - 1])!;
          branches.push({ ships: path, archetype: tip.archetype });
          continue;
        }
        // Each child continues; if multiple, each becomes its own branch.
        for (const k of kids) stack.push({ node: k, path: [...path, k.shipId] });
      }
    };
    for (const r of roots) walk(r);
    out.push({ type, branches });
  }
  // Stable type order: Battleship, Cruiser, Destroyer, AirCarrier, Submarine.
  const TYPE_ORDER = ["Battleship", "Cruiser", "Destroyer", "AirCarrier", "Submarine"];
  out.sort((a, b) => TYPE_ORDER.indexOf(a.type) - TYPE_ORDER.indexOf(b.type));
  return out;
}
