#!/usr/bin/env python3
"""Bake `packages/webui/src/data/ship_consumable_kit.json` — per-ship
consumable CAPABILITY (radar / 水听 hydro / 烟 smoke) for the Tab overlay's
two-sided team-intel cards.

The cards answer "how many radars/hydros/smokes can each team field", as an
estimate range: utility cruisers mount ONE consumable per slot chosen from
several, so a slot listing radar + spotter + fighter only MIGHT be a radar.
Per ship the bake therefore records, per family:

* ``2`` — definite: some slot offers ONLY this family (every loadout has it);
* ``1`` — possible: the family appears in a slot alongside alternatives;
* ``0`` — the ship cannot mount it at all (entry omitted from the asset).

``radarM`` is the ship's longest radar detection radius in METERS (stock
values, best variant) — only present when the ship can mount radar. The
Tab overlay marks each side's max ``radarM`` so the player knows how far out
they can be lit. ``hydroM`` is the same bake for hydroacoustic search
(``SonarSearch``): the longest ship/torpedo detection radius in meters,
only present when the ship can mount hydro.

Sources:

* ``packages/webui/src/res/data/gameparams/<shipId>.json`` (the offline
  pack, gitignored — generated by ``scripts/extract_gameparams.py``) — the
  per-ship ``ShipAbilities`` slot layout with each slot's mountable
  alternatives. This alone answers the counts; the script works without a
  full GameParams (``radarM`` is then simply omitted).
* the full `GameParams.json` (`%LOCALAPPDATA%/WoWSP-extract`, produced by
  `just extract`) — the ability ENTITY definitions, whose per-variant
  `logic.distShip` is the radar / hydro detection radius in BigWorld units
  (1 BW unit = 30 m — same conversion the vendored wowsunpack
  `AbilityCategory::detection_radius()` applies).

Families counted: `RLSSearch` (radar), `SonarSearch` (hydro),
`SmokeGenerator` (smoke). Deliberately NOT counted: `Hydrophone` (the
submarines' own consumable — a different mechanic from hydroacoustic
search) and `PlaneSmokeGenerator` (squadron smoke, not a ship smoke).

Usage:
    python scripts/extract_ship_consumable_kit.py
    python scripts/extract_ship_consumable_kit.py --full /path/to/GameParams.json
    python scripts/extract_ship_consumable_kit.py --no-full   # counts only
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter
from pathlib import Path
from typing import Any

# Same family normalizer the live-stats bake uses (`PCY020_RLSSearchPremium`
# → `RLSSearch`) — reuse it so the two assets can never disagree.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from extract_ship_live_stats import ability_family  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent

DEFAULT_PACK = REPO_ROOT / "packages/webui/src/res/data/gameparams"
DEFAULT_FULL = (
    Path(os.environ.get("LOCALAPPDATA", Path.home() / ".local/share"))
    / "WoWSP-extract"
    / "GameParams.json"
)
DEFAULT_OUT = REPO_ROOT / "packages/webui/src/data/ship_consumable_kit.json"

FAMILY_RADAR = "RLSSearch"
FAMILY_HYDRO = "SonarSearch"
FAMILY_SMOKE = "SmokeGenerator"
COUNTED = (FAMILY_RADAR, FAMILY_HYDRO, FAMILY_SMOKE)

# BigWorld distance unit → meters (wows-core units.rs BW_TO_METERS; the
# vendored wowsunpack `detection_radius()` applies the same factor).
BW_TO_METERS = 30.0


def slot_families(gp: dict[str, Any]) -> list[set[str]]:
    """Every non-special slot's counted consumable families (slot order).

    A slot's `abils` entries are the alternatives the player chooses ONE
    from (`[abilityName, variantName]` pairs); families outside the three
    counted ones are dropped here so odd entity names (event modes,
    commander talents) can never pollute the counts.
    """
    abilities = gp.get("ShipAbilities")
    if not isinstance(abilities, dict):
        return []
    out: list[set[str]] = []
    for key in sorted(k for k in abilities if k.startswith("AbilitySlot")):
        slot = abilities.get(key)
        if not isinstance(slot, dict) or slot.get("isSpecial"):
            continue
        fams: set[str] = set()
        for entry in slot.get("abils") or []:
            name = entry[0] if isinstance(entry, (list, tuple)) and entry else entry
            fam = ability_family(name)
            if fam in COUNTED:
                fams.add(fam)
        if fams:
            out.append(fams)
    return out


def kit_values(fams: list[set[str]]) -> dict[str, int]:
    """definite(2) / possible(1) / none(0) per counted family."""
    out: dict[str, int] = {}
    for fam in COUNTED:
        if any(s == {fam} for s in fams):
            out[fam] = 2
        elif any(fam in s for s in fams):
            out[fam] = 1
    return out


def family_meters(
    gp: dict[str, Any],
    full: dict[str, Any] | None,
    family: str,
) -> int | None:
    """Longest stock detection radius (m) across the ship's slots for one
    consumable family.

    Each slot entry names its ability entity + variant; the variant dict's
    `logic.distShip` (BW units) wins, with the entity's `Default` variant as
    the fallback for plain-string entries. Per-ship variants (hydro's
    `PCY008_SonarSearch` keys them by ship / tier-group name at the entity's
    top level) ride the same lookup — the slot entry carries the variant
    name. Returns None when no entry resolves to a distShip (also whenever
    the full GameParams is absent).
    """
    abilities = gp.get("ShipAbilities")
    if not isinstance(abilities, dict) or full is None:
        return None
    best = 0.0
    for key in sorted(k for k in abilities if k.startswith("AbilitySlot")):
        slot = abilities.get(key)
        if not isinstance(slot, dict):
            continue
        for entry in slot.get("abils") or []:
            name, variant = (
                (entry[0], entry[1]) if isinstance(entry, (list, tuple)) and len(entry) > 1
                else (entry, None)
            )
            if ability_family(name) != family:
                continue
            entity = full.get(name if isinstance(name, str) else "")
            if not isinstance(entity, dict):
                continue
            spec = None
            for cand in (variant, "Default"):
                if isinstance(cand, str) and isinstance(entity.get(cand), dict):
                    spec = entity[cand]
                    break
            if spec is None:
                continue
            dist = spec.get("logic", {}).get("distShip")
            if isinstance(dist, (int, float)) and not isinstance(dist, bool):
                best = max(best, dist * BW_TO_METERS)
    return round(best) if best > 0 else None


def radar_meters(gp: dict[str, Any], full: dict[str, Any] | None) -> int | None:
    """Longest stock radar detection radius (m) across the ship's slots."""
    return family_meters(gp, full, FAMILY_RADAR)


def hydro_meters(gp: dict[str, Any], full: dict[str, Any] | None) -> int | None:
    """Longest stock hydroacoustic detection radius (m) across slots."""
    return family_meters(gp, full, FAMILY_HYDRO)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--pack", type=Path, default=DEFAULT_PACK,
                    help="offline gameparams slice dir (gitignored; "
                         "point at a checkout that has it)")
    ap.add_argument("--full", type=Path, default=DEFAULT_FULL,
                    help="full GameParams.json (radar/hydro ranges)")
    ap.add_argument("--no-full", action="store_true",
                    help="bake without the full GameParams (omit radarM/hydroM)")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args(argv)

    if not args.pack.is_dir():
        print(f"error: gameparams pack not found: {args.pack}", file=sys.stderr)
        return 2
    full: dict[str, Any] | None = None
    if not args.no_full:
        if not args.full.is_file():
            print(f"error: full GameParams not found: {args.full} "
                  "(run `just extract`, or pass --no-full to bake counts only)",
                  file=sys.stderr)
            return 2
        print(f"loading full GameParams: {args.full} …")
        full = json.loads(args.full.read_text(encoding="utf-8"))

    out: dict[str, dict[str, Any]] = {}
    stats: Counter[str] = Counter()
    radar_seen: list[tuple[int, str]] = []
    hydro_seen: list[tuple[int, str]] = []
    for path in sorted(args.pack.glob("*.json")):
        ship_id = path.stem
        if not ship_id.isdigit():
            continue
        try:
            gp = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as err:
            print(f"warn: skipping {path.name}: {err}", file=sys.stderr)
            continue
        if (gp.get("typeinfo") or {}).get("type") != "Ship":
            stats["skipped_non_ship"] += 1
            continue

        fams = slot_families(gp)
        record: dict[str, Any] = {}
        for fam, val in kit_values(fams).items():
            key = {"RLSSearch": "r", "SonarSearch": "h", "SmokeGenerator": "s"}[fam]
            record[key] = val
            stats[f"{key}{val}"] += 1
        if record.get("r"):
            m = radar_meters(gp, full)
            if m:
                record["radarM"] = m
                stats["radarM"] += 1
                radar_seen.append((m, str(gp.get("name") or ship_id)))
        if record.get("h"):
            m = hydro_meters(gp, full)
            if m:
                record["hydroM"] = m
                stats["hydroM"] += 1
                hydro_seen.append((m, str(gp.get("name") or ship_id)))
        # Ships that cannot mount any of the three get no entry at all —
        # a lookup miss in the consumer means "all zeros".
        if record:
            out[ship_id] = record

    ordered = {sid: out[sid] for sid in sorted(out, key=lambda s: int(s))}
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        json.dumps(ordered, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
        + "\n",
        encoding="utf-8",
        newline="\n",
    )

    print(f"wrote {args.out.relative_to(REPO_ROOT)} — {len(ordered)} ships with a "
          f"kit, {args.out.stat().st_size / 1024:.0f} KiB")
    for key in sorted(stats):
        print(f"  {key}: {stats[key]}")
    if radar_seen:
        print("  longest stock radars (m):")
        for m, name in sorted(radar_seen, reverse=True)[:12]:
            print(f"    {m:>6}  {name}")
    if hydro_seen:
        print("  longest stock hydros (m):")
        for m, name in sorted(hydro_seen, reverse=True)[:12]:
            print(f"    {m:>6}  {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
