#!/usr/bin/env python
"""Generate the per-version Avatar/Vehicle client-method id table used by the
replay packet decoder (`packages/app/tauri/src/commands/method_tables.rs`).

Why: the wire method id in EntityMethod (0x08) packets is the method's index in
the entity's client-method table sorted by wire size (BigWorld "exposed index";
stable sort so equal-size methods keep XML order). The tables drift with every
game version, so the decoder must pick the table matching the replay's client
version instead of hardcoding ids.

Source of truth: MarshalPartyByJack's `replay_unpack` entity definitions (the
`.def` XML files shipped per game version), as vendored inside the local
minimap_renderer reference checkout:

    <reference>/src/replay_unpack/clients/wows/versions/<ver>/scripts/entity_defs/

Usage:

    python scripts/gen_method_tables.py <path-to-minimap_renderer>/src \
        > packages/app/tauri/src/commands/method_tables.rs

The output is committed; CI never runs this script.
"""

import os
import re
import sys


AVATAR_METHODS = [
    "receiveArtilleryShots",
    "receiveTorpedoes",
    "receiveExplosions",
    "receiveTorpedoDirection",
    "receive_addSquadron",
    "receive_updateSquadron",
    "receive_addMinimapSquadron",
    "receive_updateMinimapSquadron",
    "receive_removeMinimapSquadron",
]


def to_snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def version_key(dir_name: str):
    return tuple(int(x) for x in dir_name.split("_"))


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    # Pure-LF output so `>` redirection on Windows doesn't inject CRLF that
    # `cargo fmt` would then strip (keeping regeneration fmt-stable).
    sys.stdout.reconfigure(newline="\n")
    src_root = sys.argv[1]
    sys.path.insert(0, src_root)
    from replay_unpack.clients.wows.helper import get_definitions  # noqa: E402

    versions_dir = os.path.join(
        src_root, "replay_unpack", "clients", "wows", "versions"
    )
    versions = sorted(
        (d for d in os.listdir(versions_dir) if d[0].isdigit()), key=version_key
    )

    rows = []
    for v in versions:
        try:
            defs = get_definitions(v)
        except Exception as exc:  # noqa: BLE001 - report and skip broken defs
            print(f"WARNING: {v}: {exc}", file=sys.stderr)
            continue
        entry = {"version": version_key(v)}
        for entity, methods in (("Avatar", AVATAR_METHODS),):
            try:
                exposed = defs.get_entity_def_by_name(entity).client().get_exposed_index_map()
            except KeyError:
                continue
            names = {m.get_name(): idx for idx, m in enumerate(exposed)}
            for m in methods:
                if m in names:
                    entry[f"{entity.lower()}_{to_snake(m)}"] = names[m]
        rows.append(entry)

    fields = [f"avatar_{to_snake(m)}" for m in AVATAR_METHODS]

    out = sys.stdout
    w = out.write
    w("//! AUTO-GENERATED by `scripts/gen_method_tables.py` — do not edit by hand.\n")
    w("//!\n")
    w("//! Per-game-version ids of the Avatar/Vehicle client methods the replay\n")
    w("//! decoder consumes. The wire id in EntityMethod (0x08) packets is the\n")
    w("//! method's index in the entity's client-method table sorted by wire size\n")
    w("//! (BigWorld exposed index; stable sort — equal sizes keep XML order). The\n")
    w("//! mapping drifts every game version; see the generator's docstring for the\n")
    w("//! source of truth (replay_unpack entity definitions).\n\n")
    w("/// The method ids one game version's entity definitions resolve to.\n")
    w("#[derive(Debug, Clone, Copy)]\n")
    w("pub struct MethodIds {\n")
    for f in fields:
        w(f"    pub {f}: i32,\n")
    w("}\n\n")
    w("/// (major, minor, patch) → ids, ascending. Produced from every version the\n")
    w("/// reference entity definitions ship.\n")
    w("pub static METHOD_TABLES: &[((u16, u16, u16), MethodIds)] = &[\n")
    for e in rows:
        ver = e["version"]
        # Emission shape matches `cargo fmt` canonical formatting exactly
        # (tuple + struct literal wrapped across lines) so regeneration is
        # fmt-stable.
        w(f"    (\n        ({ver[0]}, {ver[1]}, {ver[2]}),\n        MethodIds {{\n")
        for f in fields:
            w(f"            {f}: {e.get(f, -1)},\n")
        w("        },\n    ),\n")
    w("];\n")
    w("""
/// Resolve the method-id table for a `clientVersionFromExe` descriptor value
/// (comma-separated `major,minor,patch[,build]`). Exact version first, else the
/// newest table not newer than the replay, else the oldest table (legacy
/// replays predate the shipped definitions) / newest table (replays from a
/// client newer than every shipped table — ids mostly append, so the newest
/// table is the best guess). `None` (no version string) assumes the newest.
pub fn method_ids_for_version(client_version: Option<&str>) -> &'static MethodIds {
    let key = client_version.and_then(parse_version_key);
    let idx = match key {
        Some(k) => {
            let mut chosen = 0usize;
            for (i, (v, _)) in METHOD_TABLES.iter().enumerate() {
                if *v <= k {
                    chosen = i;
                }
            }
            chosen
        },
        None => METHOD_TABLES.len() - 1,
    };
    &METHOD_TABLES[idx].1
}

/// `\"15,0,0,11791718\"` → `(15, 0, 0)`; malformed input yields `None`.
fn parse_version_key(v: &str) -> Option<(u16, u16, u16)> {
    let mut parts = v.split(',');
    let (Some(a), Some(b), Some(c)) = (parts.next(), parts.next(), parts.next()) else {
        return None;
    };
    Some((
        a.trim().parse().ok()?,
        b.trim().parse().ok()?,
        c.trim().parse().ok()?,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Version selection: exact, older-than-all, newer-than-all, malformed.
    #[test]
    fn selects_table_by_version() {
        // Newer than every shipped table falls back to the newest one.
        let newest = method_ids_for_version(Some("99,0,0,1"));
        let last = METHOD_TABLES[METHOD_TABLES.len() - 1].1;
        assert_eq!(
            newest.avatar_receive_explosions,
            last.avatar_receive_explosions
        );
        // Older than every shipped table falls back to the oldest one.
        let oldest = method_ids_for_version(Some("0,9,9,1"));
        let first = &METHOD_TABLES[0].1;
        assert_eq!(
            oldest.avatar_receive_artillery_shots,
            first.avatar_receive_artillery_shots
        );
        assert!(method_ids_for_version(None).avatar_receive_artillery_shots > 0);
        assert!(method_ids_for_version(Some("garbage")).avatar_receive_artillery_shots > 0);
    }

    /// Every table carries the ids the decoder needs (no -1 placeholders in the
    /// shipped versions — a -1 would silently disable that event stream).
    #[test]
    fn all_tables_fully_populated() {
        for (v, t) in METHOD_TABLES {
            for id in [
                t.avatar_receive_artillery_shots,
                t.avatar_receive_torpedoes,
                t.avatar_receive_explosions,
                t.avatar_receive_add_minimap_squadron,
                t.avatar_receive_update_minimap_squadron,
                t.avatar_receive_remove_minimap_squadron,
            ] {
                assert!(id > 0, "unpopulated id in table {v:?}");
            }
        }
    }
}
""")


if __name__ == "__main__":
    main()
