#!/usr/bin/env python3
"""GLSL shader + theme bundler for WoWSP.

Adapted from shittim-chest's `scripts/glsl_bundle.py`. Scans
`res/shaders/**/*.theme.toml`, reads the associated .glsl and metadata, and
generates `packages/webui/.generated/shaders/shaders.ts` — no external tools.

Adding a new theme = add .glsl + .theme.toml under `res/shaders/`, zero code
changes required.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib
    except ModuleNotFoundError:
        tomllib = None

REPO_ROOT = Path(__file__).resolve().parent.parent
SHADERS_DIR = REPO_ROOT / "res" / "shaders"
BUILD_DIR = REPO_ROOT / "packages" / "webui" / ".generated" / "shaders"


def _load_toml(path: Path) -> dict:
    raw = path.read_bytes()
    if tomllib is not None:
        return tomllib.loads(raw.decode())
    fallback = path.with_suffix(".json")
    if fallback.is_file():
        return json.loads(fallback.read_text())
    print(f"ERROR: no tomllib/tomli and no JSON fallback for {path}", file=sys.stderr)
    sys.exit(1)


def _slug(name: str) -> str:
    return name.replace("-", "_").replace(".", "_")


def _read_shader(theme_dir: Path, filename: str) -> str | None:
    p = theme_dir / filename
    if not p.is_file():
        print(f"WARN: shader not found: {p}", file=sys.stderr)
        return None
    return p.read_text()


def find_themes(shaders_dir: Path) -> list[tuple[Path, dict]]:
    themes: list[tuple[Path, dict]] = []
    for root, _, filenames in os.walk(shaders_dir):
        for fn in sorted(filenames):
            if not fn.endswith(".theme.toml"):
                continue
            path = Path(root) / fn
            try:
                cfg = _load_toml(path)
            except Exception as e:
                print(f"WARN: skipping {path}: {e}", file=sys.stderr)
                continue
            themes.append((path, cfg))
    return themes


def generate(output_dir: Path, themes: list[tuple[Path, dict]], verbose: bool) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    shader_exports: list[str] = []
    preset_configs: list[dict] = []
    seen_ids: set[str] = set()

    for theme_path, cfg in themes:
        theme_id = cfg["id"]
        if theme_id in seen_ids:
            print(f"WARN: duplicate theme id: {theme_id}", file=sys.stderr)
            continue
        seen_ids.add(theme_id)

        theme_dir = theme_path.parent
        shader_field = cfg.get("shader")

        if isinstance(shader_field, dict):
            dark_file = shader_field.get("dark", "")
            light_file = shader_field.get("light", "")
            for label, fname in (("dark", dark_file), ("light", light_file)):
                if fname:
                    code = _read_shader(theme_dir, fname)
                    if code:
                        var = _slug(f"{theme_id}.{label}")
                        shader_exports.append(f"export const {var}_glsl: string = {repr(code)};\n")
                        rel = (theme_dir / fname).relative_to(SHADERS_DIR)
                        out = output_dir / rel
                        out.parent.mkdir(parents=True, exist_ok=True)
                        out.write_text(code)
                        if verbose:
                            print(f"  {rel} -> {out.relative_to(REPO_ROOT)}")
            preset: dict = {"id": theme_id, "dualMode": True}
            if dark_file:
                preset["darkShader"] = dark_file
            if light_file:
                preset["lightShader"] = light_file
        else:
            shader_file = shader_field
            code = _read_shader(theme_dir, shader_file)
            if code is None:
                continue
            var = _slug(theme_id)
            shader_exports.append(f"export const {var}_glsl: string = {repr(code)};\n")
            rel = (theme_dir / shader_file).relative_to(SHADERS_DIR)
            out = output_dir / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(code)
            if verbose:
                print(f"  {rel} -> {out.relative_to(REPO_ROOT)}")
            preset = {"id": theme_id, "dualMode": False, "shader": shader_file}

        if "overlay" in cfg:
            preset["overlay"] = cfg["overlay"]
        if "render" in cfg:
            preset["render"] = cfg["render"]
        preset_configs.append(preset)

    header = (
        "// AUTO-GENERATED by scripts/glsl_bundle.py — do not edit\n"
        "// Source: res/shaders/**/*.glsl + *.theme.toml\n"
        "// To add a theme: add .glsl + .theme.toml in res/shaders/, rebuild.\n\n"
    )
    (output_dir / "shaders.ts").write_text(header + "".join(shader_exports))
    (output_dir / "themes.json").write_text(
        json.dumps(preset_configs, indent=2, ensure_ascii=False) + "\n"
    )
    if verbose:
        print(f"  themes.json: {[p['id'] for p in preset_configs]}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Bundle GLSL shaders + themes into TypeScript")
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    themes = find_themes(SHADERS_DIR)
    if not themes:
        print(f"No .theme.toml files found in {SHADERS_DIR}")
        sys.exit(1)

    generate(BUILD_DIR, themes, args.verbose)
    print(f"Done: {len(themes)} themes -> {BUILD_DIR.relative_to(REPO_ROOT)}/")


if __name__ == "__main__":
    main()
