# -*- coding: utf-8 -*-
"""old slug -> new taxonomical slug (category.genus.species)."""

SLUG_MAP = {
    # ── battle.marker.* (was markers-*) ──
    "markers-adjustablesubhighlight": "battle.marker.sub-highlight",
    "markers-adjustable-markers": "battle.marker.adjustable",
    "markers-adjustable-markers-aslain": "battle.marker.adjustable-aslain",
    "markers-adjustable-markers-capt-oveur": "battle.marker.adjustable-oveur",
    "markers-advanced-torpedo-marker": "battle.marker.torpedo-advanced",
    "markers-consumablesmonitor": "battle.marker.consumables",
    "markers-detectionmonitor": "battle.marker.detection",
    "markers-numerical-remaining-battery-on-submarines": "battle.marker.sub-battery",
    "markers-regen-monitor": "battle.marker.regen",
    "markers-smoke-marker": "battle.marker.smoke",
    "markers-speed-indicator": "battle.marker.speed",
    "markers-torpedoes-detection-indicator": "battle.marker.torpedo-spotted",
    "markers-traffic-lights": "battle.marker.traffic",
    "markers-traffic-lights-v2": "battle.marker.traffic-v2",
    "markers-traffic-lights-v2-cb": "battle.marker.traffic-v2-cb",
    "markers-traffic-lights-v3": "battle.marker.traffic-v3",
    "markers-traffic-lights-v4": "battle.marker.traffic-v4",
    "markers-enhanced-depth-charge-marker": "battle.marker.depth-charge",
    # ── battle.panel.* / battle.minipanel.* (was team-*) ──
    "team-panel-ttaro": "battle.panel.ttaro",
    "team-panel-autospy": "battle.panel.autospy",
    "team-panel-badobest": "battle.panel.badobest",
    "team-panel-roslich": "battle.panel.roslich",
    "team-panel-hakabase": "battle.panel.hakabase",
    "team-panel-deceaseddaisy": "battle.panel.deceased",
    "team-panel-teampaneldivisionbadges": "battle.panel.division-badges",
    "team-mini-panel-autospy-v1": "battle.minipanel.autospy-v1",
    "team-mini-panel-autospy-v2": "battle.minipanel.autospy-v2",
    "team-mini-panel-team-hp-plus": "battle.minipanel.team-hp",
    # ── battle.timer.* (was ui-timers-*) ──
    "ui-timers-shot-timer": "battle.timer.shot",
    "ui-timers-battletimer": "battle.timer.battle",
    "ui-timers-score-timer": "battle.timer.score",
    "ui-timers-radar-timer": "battle.timer.radar",
    "ui-timers-reload-timer": "battle.timer.reload",
    "ui-timers-hiding-timer": "battle.timer.hiding",
    "ui-timers-battleclock": "battle.timer.clock",
    "ui-timers-stopwatch": "battle.timer.stopwatch",
    "ui-timers-smoke-indicator": "battle.timer.smoke",
    "ui-timers-numerical-capture-time-on-objectives": "battle.timer.capture",
    "ui-timers-travel-to-capture-point": "battle.timer.travel",
    "ui-timers-ragemodecountdown": "battle.timer.orders",
    "ui-timers-timebasedconsumableenhance": "battle.timer.consumables",
    # ── battle.meter.* (was ui-meters-*) ──
    "ui-meters-damagemeter": "battle.meter.damage",
    "ui-meters-damagemonitor": "battle.meter.damage-monitor",
    "ui-meters-pingometer": "battle.meter.ping-fps",
    "ui-meters-mxmeter": "battle.meter.mx",
    "ui-meters-mxmeter-percent": "battle.meter.mx-percent",
    # ── battle.cv.* (was ui-cv-*) ──
    "ui-cv-telegraph": "battle.cv.telegraph",
    "ui-cv-poi-static-indicator": "battle.cv.poi-static",
    "ui-cv-central-squadron-healtbar": "battle.cv.hp-center",
    "ui-cv-numerical-hp-on-squadrons": "battle.cv.hp-numeric",
    "ui-cv-squadronconsumablesassistant": "battle.cv.consumables",
    # ── battle.expert.* (was ui-battleexpert*) ──
    "ui-battleexpert": "battle.expert.core",
    "ui-battleexpert-v2-bottom-left": "battle.expert.v2-bottom-left",
    "ui-battleexpert-v2-center": "battle.expert.v2-center",
    "ui-battleexpert-v2-right": "battle.expert.v2-right",
    "ui-battleexpert-v2-show-compass": "battle.expert.v2-compass",
    # ── battle.info.* (was ui-infopanel-*) ──
    "ui-infopanel-enemy-autospy": "battle.info.target-v1",
    "ui-infopanel-enemy-ollin": "battle.info.target-v2",
    "ui-infopanel-self": "battle.info.self",
    # ── battle.* senses ──
    "ui-radar-3d": "battle.radar.3d",
    "ui-hydro-3d": "battle.hydro.3d",
    "ui-rpf-3d": "battle.rpf.3d",
    "ui-intuitions": "battle.rpf.counter",
    "ui-afk-monitor": "battle.monitor.afk",
    "ui-advancedshipstatuspanel": "battle.statuspanel.advanced",
    "ui-build-viewer": "battle.build.viewer",
    "ui-module-state-viewer": "battle.module.viewer",
    "ui-penetrationcalculator": "battle.calculator.penetration",
    "ui-regenassistant": "battle.heal.assistant",
    "ui-underwaterhitviewer": "battle.hitview.underwater",
    "ui-visible-angle-of-impact-enemy": "battle.impact-angle.all",
    "ui-visible-angle-of-impact-enemy-citadel": "battle.impact-angle.citadel",
    "ui-visible-angle-of-impact-enemy-torpedo": "battle.impact-angle.torpedo",
    "ui-reaction-time": "battle.reaction.torpedo",
    "ui-secondary-armament": "battle.secondary.status",
    "ui-streamermode": "battle.privacy.streamer",
    "ui-playtogether": "battle.social.invite",
    "ui-remove-camera-instructions": "battle.spectator.clean",
    "ui-compactquickcommands": "battle.commands.compact",
    "ui-companion": "battle.campaign.companion",
    "ui-crewcampaignsskillsinbattle": "battle.campaign.crew-skills",
    "ui-postbattleprogressnumbers": "battle.results.task-numbers",
    "ui-more-compact-ship-battle-parameters": "battle.parameters.compact",
    # ── minimap.* ──
    "minimap-ttaro": "minimap.core.ttaro",
    "minimap-rpf-2d": "minimap.rpf.2d",
    "minimap-last-spotted-timer": "minimap.timer.last-spotted",
    "minimap-enlargedshipnames": "minimap.names.large",
    "minimap-submarine-pingers-on-minimap": "minimap.ping.submarine",
    "minimap-advanced-attention-marker": "minimap.attention.3d",
    "minimap-between-team-members-on-battle-loading": "minimap.loadingscreen.preview",
    # ── port.carousel.* (was port-mods-carousel-*) ──
    "port-mods-carousel-filters": "port.carousel.filters",
    "port-mods-carousel-compactcarousel": "port.carousel.compact",
    "port-mods-carousel-fast-scroll": "port.carousel.fast-scroll",
    "port-mods-carousel-nextshipxp": "port.carousel.next-xp",
    "port-mods-carousel-pm-shipswinrate": "port.carousel.winrate",
    "port-mods-carousel-carouselskills": "port.carousel.skill-points",
    "port-mods-carousel-shipimages": "port.carousel.3d-icons",
    "port-mods-carousel-randomshipselector": "port.carousel.random",
    "port-mods-carousel-remove-no-commander": "port.carousel.hide-no-commander",
    "port-mods-carousel-remove-ship-rarity-strip": "port.carousel.hide-rarity",
    "port-mods-carousel-extended": "port.carousel.extended",
    # ── port.* (was port-mods-*) ──
    "port-mods-aslainsversionchecker": "port.updater.version-check",
    "port-mods-sessionstats": "port.sessionstats.core",
    "port-mods-sessionstats-ollin": "port.sessionstats.v2",
    "port-mods-sessionstats-old": "port.sessionstats.v1",
    "port-mods-shipmanagement": "port.manager.ship",
    "port-mods-shiptreeenhancements": "port.techtree.enhanced",
    "port-mods-extended-techtree-ollin": "port.techtree.all-ollin",
    "port-mods-extended-techtree-another": "port.techtree.all-another",
    "port-mods-current-server-population": "port.population.server",
    "port-mods-resources": "port.resources.display",
    "port-mods-karma-info": "port.karma.info",
    "port-mods-flags-price": "port.flags.price",
    "port-mods-equipment-tab-improvements": "port.equipment.tab",
    "port-mods-docknavibuttons": "port.dock.navigation",
    "port-mods-banner-switcher-campaigns-in-port": "port.missions.banner",
    "port-mods-auto-container-collector": "port.lootbox.auto",
    "port-mods-good-news": "port.news.hide",
    "port-mods-not-in-battle": "port.status.hide-battle",
    "port-mods-adjustable-div-chat": "port.chat.div-window",
    "port-mods-battletype-button": "port.battlebutton.default",
    "port-mods-battletype-button-vito74m": "port.battlebutton.vito74m",
    "port-mods-crewassign": "port.crew.assign",
    "port-mods-crewcounter": "port.crew.counter",
    "port-mods-training-room": "port.training.crew",
    "port-mods-customizeshipintraining": "port.training.customize",
    "port-mods-all-ships-in-training-room": "port.training.all-ships",
    "port-mods-tournament-ready": "port.tournament.check",
    "port-mods-overmatch": "port.info.overmatch",
    "port-mods-commander-perks-in-frames": "port.perks.framed",
    "port-mods-commander-perks-colored-vito78m-v1": "port.perks.vito-v1",
    "port-mods-commander-perks-colored-vito78m-v2": "port.perks.vito-v2",
    # ── text.chat.* (was chat-*) ──
    "chat-ttaro": "text.chat.ttaro",
    "chat-chatcensorshipremover": "text.chat.anti-censorship",
    "chat-google-japanese-input": "text.chat.google-input",
    # ── text.* (was texts-*) ──
    "texts-shipname-fanhexie": "text.shipname.fanhexie",
    "texts-shipname-real-ship-names": "text.shipname.real",
    "texts-originships": "text.shipname.origin",
    "texts-lowrcaseshipnames": "text.shipname.lowercase",
    "texts-ladycommanders": "text.shipname.romanized",
    "texts-gun-calibers-in-inches": "text.caliber.mm-inch",
    "texts-east-asia-font-pack": "text.font.east-asia",
    # ── patch.* ──
    "ime-config": "patch.ime.compat",
}

# front-matter category normalization (old -> new)
CATEGORY_RENAME = {"texts": "text", "patches": "patch"}
