/**
 * Multilingual ship-name search with Chinese near-sound (pinyin) matching.
 *
 * Standalone module — data is pre-generated by
 * `scripts/model_convert/extract_ship_pinyin.py`:
 *  - char_pinyin.json   : CJK char → first-tone pinyin (query conversion)
 *  - ship_pinyin.json   : shipId → { zh, pinyin, initials }
 *
 * Matching order:
 *  1. Any-language name containment (the hit is displayed in the matched
 *     language — e.g. "Bogue" → en-US, "博格" → zh-CN).
 *  2. Near-sound: the query (converted to pinyin, so 同音字 like "伯阁"
 *     work too) against the ship's pinyin / initials ("boge" or "bg").
 */
import charPinyin from "@/data/char_pinyin.json";
import shipPinyin from "@/data/ship_pinyin.json";

export interface ShipNameHit {
  matchedLang: string;
  matchedName: string;
}

const CHAR_PINYIN = charPinyin as Record<string, string>;
const SHIP_PINYIN = shipPinyin as Record<string, { zh: string; pinyin: string; initials: string }>;

/** Convert CJK text to pinyin (first tone per char; non-CJK passes through). */
export function toPinyin(text: string): string {
  return [...text]
    .map((c) => CHAR_PINYIN[c] ?? c)
    .join("")
    .toLowerCase();
}

/** Pinyin index for a ship (null when the ship has no Chinese name). */
export function pinyinOfShip(shipId: number): { zh: string; pinyin: string; initials: string } | null {
  return SHIP_PINYIN[String(shipId)] ?? null;
}

/** Match a query against a ship's multilingual names + pinyin. */
export function matchShipNames(
  query: string,
  names: Record<string, string> | undefined,
  shipId: number,
): ShipNameHit | null {
  const q = query.trim().toLowerCase();
  if (!q) return null;
  // 1) any-language name containment (display in the matched language)
  if (names) {
    for (const [lang, name] of Object.entries(names)) {
      if (name && name.toLowerCase().includes(q)) {
        return { matchedLang: lang, matchedName: name };
      }
    }
  }
  // 2) near-sound: query pinyin vs ship pinyin / initials
  const entry = SHIP_PINYIN[String(shipId)];
  if (entry) {
    const qpy = toPinyin(q);
    if (
      entry.pinyin.includes(qpy) ||
      entry.pinyin.startsWith(qpy) ||
      qpy.includes(entry.pinyin) ||
      entry.initials.includes(qpy)
    ) {
      return { matchedLang: "zh-CN", matchedName: entry.zh };
    }
  }
  return null;
}

/** Filter a list of ships by a query; returns { shipId → hit } for matches. */
export function searchShips<T extends { shipId: number }>(
  ships: T[],
  query: string,
  namesOf: (s: T) => Record<string, string> | undefined,
): Map<number, ShipNameHit> {
  const hits = new Map<number, ShipNameHit>();
  for (const s of ships) {
    const hit = matchShipNames(query, namesOf(s), s.shipId);
    if (hit) hits.set(s.shipId, hit);
  }
  return hits;
}
