[site]
title = "WoWSP"
description = "World of WarShip Panel — replay review & in-game overlay"
cname = "wowsp.langyo.xyz"
favicon = "./logo.webp"
title_template = "{title} — World of WarShip Panel"

[languages]
default = "en"
order = ["en", "zhs", "zht", "ja", "ko", "fr", "es", "ru", "ar"]
