/**
 * Tauri IPC command names. The webui calls these via `transport.invoke(cmd)`,
 * which routes to `window.__TAURI__.core.invoke(cmd, args)` in the desktop
 * shell and to a fetch-based shim against the mock backend in the browser.
 *
 * Keep these strings in lock-step with the `#[tauri::command]` functions in
 * `packages/app/tauri/src/commands/`.
 */
export const RPC = {
  get_os_preferences: "get_os_preferences",
  appdata_read: "appdata_read",
  appdata_write: "appdata_write",
  appdata_delete: "appdata_delete",
  is_game_running: "is_game_running",
  get_game_process: "get_game_process",
  detect_game_install: "detect_game_install",
  set_game_path: "set_game_path",
  pick_game_folder: "pick_game_folder",
  ribbon_skin_dir: "ribbon_skin_dir",
  read_replay_header: "read_replay_header",
  read_replay_positions: "read_replay_positions",
  list_replays: "list_replays",
  list_replays_meta: "list_replays_meta",
  pick_replay_files: "pick_replay_files",
  pick_export_path: "pick_export_path",
  write_export_bytes: "write_export_bytes",
  read_temp_arena_info: "read_temp_arena_info",
  start_arena_watcher: "start_arena_watcher",
  stop_arena_watcher: "stop_arena_watcher",
  capture_game_window: "capture_game_window",
  create_overlay_window: "create_overlay_window",
  destroy_overlay_window: "destroy_overlay_window",
  set_overlay_visible: "set_overlay_visible",
  start_overlay_tab_watch: "start_overlay_tab_watch",
  stop_overlay_tab_watch: "stop_overlay_tab_watch",
  start_manual_locate: "start_manual_locate",
  cancel_manual_locate: "cancel_manual_locate",
  set_manual_roster_rect: "set_manual_roster_rect",
  clear_manual_roster_rect: "clear_manual_roster_rect",
  lookup_player_stats: "lookup_player_stats",
  lookup_players_stats_batch: "lookup_players_stats_batch",
  suggest_players: "suggest_players",
  suggest_clans: "suggest_clans",
  lookup_clan_info: "lookup_clan_info",
  get_game_version: "get_game_version",
  get_ship_encyclopedia: "get_ship_encyclopedia",
  lookup_player_ship_stats: "lookup_player_ship_stats",
  read_ship_stats_history: "read_ship_stats_history",
  snapshot_player_stats: "snapshot_player_stats",
  get_ship_gameparams: "get_ship_gameparams",
  get_upgrade_prices: "get_upgrade_prices",
  get_player_trend: "get_player_trend",
  get_patches: "get_patches",
  get_community_ship_trend: "get_community_ship_trend",
  get_ship_server_stats: "get_ship_server_stats",
  capture_main_window: "capture_main_window",
  install_overlay_mod: "install_overlay_mod",
  uninstall_overlay_mod: "uninstall_overlay_mod",
  is_overlay_mod_installed: "is_overlay_mod_installed",
  get_ranked_stats: "get_ranked_stats",
  ensure_model_pack: "ensure_model_pack",
  ensure_dogtag_pack: "ensure_dogtag_pack",
  get_pack_status: "get_pack_status",
  check_pack_updates: "check_pack_updates",
  pack_download: "pack_download",
  pack_cancel: "pack_cancel",
  clear_pack: "clear_pack",
  aux_cache_overview: "aux_cache_overview",
  clear_aux_cache: "clear_aux_cache",
  get_network_config: "get_network_config",
  set_network_config: "set_network_config",
  update_check: "update_check",
  update_download: "update_download",
  update_cancel: "update_cancel",
  mod_hub_scan_installed: "mod_hub_scan_installed",
  mod_hub_classify_path: "mod_hub_classify_path",
  mod_hub_install: "mod_hub_install",
  mod_hub_set_unit_enabled: "mod_hub_set_unit_enabled",
  mod_hub_uninstall_unit: "mod_hub_uninstall_unit",
  mod_catalog_refresh: "mod_catalog_refresh",
  mod_catalog_install: "mod_catalog_install",
  mod_catalog_uninstall: "mod_catalog_uninstall",
  mod_hub_records: "mod_hub_records",
} as const;

export type RpcCommand = (typeof RPC)[keyof typeof RPC];
