export { api } from "./client";
export type {
  GameInstall,
  VehicleEntry,
  ReplayMeta,
  ReplayMetaLite,
  ArenaInfo,
  CaptureResult,
  PositionSample,
  EntityKind,
  EntityTrajectory,
  PlayerStats,
  GameVersionInfo,
  ShipInfo,
  PlayerShipStats,
  StatsSnapshot,
  TrendBucket,
  TrendResult,
  PatchNote,
  CommunityTrend,
} from "./client";
